/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Helpers.ThreadEfects;

/**
 *
 * @author ordon
 */
public class DetalleCompetencia extends javax.swing.JFrame {

    /**
     * Creates new form Resultados
     */
    public DetalleCompetencia(String nicknameJ1, String tirosJ1,String escalerasJ1,String serpientesJ1,
            String desbanqueJ1,String resultadoJ1,String nicknameJ2,String tirosJ2,String escalerasJ2,String serpientesJ2, String desbanqueJ2) {
        
        initComponents();
        setLocationRelativeTo(null);
        
        if ("Derrota".equals(resultadoJ1)) {
            lblCoronaJ1.setVisible(false);
        } else {
            lblCoronaJ2.setVisible(false);
        }
        
        lblJugador1.setText("J1: " + nicknameJ1);
        lblJugador2.setText("J2: " + nicknameJ2);
        
        lblTirosJ1.setText(tirosJ1);
        lblSerpientesJ1.setText(serpientesJ1);
        lblEscalerasJ1.setText(escalerasJ1);
        lblDesbanquesJ1.setText(desbanqueJ1);
        
        lblTirosJ2.setText(tirosJ2);
        lblSerpientesJ2.setText(serpientesJ2);
        lblEscalerasJ2.setText(escalerasJ2);
        lblDesbanquesJ2.setText(desbanqueJ2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        rSButtonMaterialOne1 = new RSMaterialComponent.RSButtonMaterialOne();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblTirosJ1 = new javax.swing.JLabel();
        lblEscalerasJ1 = new javax.swing.JLabel();
        lblDesbanquesJ1 = new javax.swing.JLabel();
        lblSerpientesJ1 = new javax.swing.JLabel();
        lblTirosJ2 = new javax.swing.JLabel();
        lblEscalerasJ2 = new javax.swing.JLabel();
        lblSerpientesJ2 = new javax.swing.JLabel();
        lblDesbanquesJ2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblJugador1 = new javax.swing.JLabel();
        lblCoronaJ1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblCoronaJ2 = new javax.swing.JLabel();
        lblJugador2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(848, 505));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/estadisticasCompetenciaTitulo.png"))); // NOI18N
        jLabel3.setText("RESULTADOS DE LA PARTIDA COMPETENCIA");

        rSButtonMaterialOne1.setBackground(new java.awt.Color(0, 153, 153));
        rSButtonMaterialOne1.setText("CERRAR DETALLE DE PARTIDA");
        rSButtonMaterialOne1.setBackgroundHover(new java.awt.Color(153, 153, 153));
        rSButtonMaterialOne1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialOne1ActionPerformed(evt);
            }
        });

        jPanel2.setForeground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Cantidad de tiros: ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Escaleras usadas:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Retroceso por serpientes:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Desbancos realizados:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 322, -1, 30));

        lblTirosJ1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTirosJ1.setText("0");
        jPanel2.add(lblTirosJ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 111, -1));

        lblEscalerasJ1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEscalerasJ1.setText("0");
        jPanel2.add(lblEscalerasJ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 111, -1));

        lblDesbanquesJ1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDesbanquesJ1.setText("0");
        jPanel2.add(lblDesbanquesJ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 113, -1));

        lblSerpientesJ1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSerpientesJ1.setText("0");
        jPanel2.add(lblSerpientesJ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 111, -1));

        lblTirosJ2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTirosJ2.setText("0");
        jPanel2.add(lblTirosJ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 111, -1));

        lblEscalerasJ2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEscalerasJ2.setText("0");
        jPanel2.add(lblEscalerasJ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 111, -1));

        lblSerpientesJ2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSerpientesJ2.setText("0");
        jPanel2.add(lblSerpientesJ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, 111, -1));

        lblDesbanquesJ2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDesbanquesJ2.setText("0");
        jPanel2.add(lblDesbanquesJ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, 113, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("Jugadores: ");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, 30));

        lblJugador1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblJugador1.setText("J1: Castroll");
        jPanel2.add(lblJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 55, 220, 40));

        lblCoronaJ1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/ganador_pequeño.png"))); // NOI18N
        jPanel2.add(lblCoronaJ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 8, 40, 50));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/desbanque.png"))); // NOI18N
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/desbanque.png"))); // NOI18N
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 130, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/tiros.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 30));

        lblCoronaJ2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/ganador_pequeño.png"))); // NOI18N
        jPanel2.add(lblCoronaJ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 8, 40, 50));

        lblJugador2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblJugador2.setText("J2: Kstro");
        jPanel2.add(lblJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 55, 190, 40));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/individual.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 720, -1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rSButtonMaterialOne1, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(9, 9, 9)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(rSButtonMaterialOne1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 860, 620));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/fondoSelecciones.png"))); // NOI18N
        jPanel1.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1450, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1450, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonMaterialOne1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialOne1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_rSButtonMaterialOne1ActionPerformed

    String[] args = {"",""};
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetalleCompetencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetalleCompetencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetalleCompetencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetalleCompetencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetalleCompetencia(args[0],args[1],args[0],args[2],args[3],args[4],args[5],args[6],args[7],args[8],args[9]).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblCoronaJ1;
    private javax.swing.JLabel lblCoronaJ2;
    private javax.swing.JLabel lblDesbanquesJ1;
    private javax.swing.JLabel lblDesbanquesJ2;
    private javax.swing.JLabel lblEscalerasJ1;
    private javax.swing.JLabel lblEscalerasJ2;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblJugador1;
    private javax.swing.JLabel lblJugador2;
    private javax.swing.JLabel lblSerpientesJ1;
    private javax.swing.JLabel lblSerpientesJ2;
    private javax.swing.JLabel lblTirosJ1;
    private javax.swing.JLabel lblTirosJ2;
    private RSMaterialComponent.RSButtonMaterialOne rSButtonMaterialOne1;
    // End of variables declaration//GEN-END:variables
}
