/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Helpers.ImgTabla;
import Modelo.Estadistica;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Diego
 */
public class Estadisticas extends javax.swing.JFrame {

    /**
     * Creates new form Estadisticas
     * @param opcion
     */
    public Estadisticas(String opcion) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.modalidad = opcion;
        
        jTable1.setDefaultRenderer(Object.class, new ImgTabla());
        
        try{
            switch(opcion){
            case "Jugador":
                lblTitulo.setText("ESTADISTICAS DEL JUEGO \"SERPIENTES Y ESCALERAS\" / DATOS DE LOS JUGADORES");
                cargarColumnas(tb,jugador);
                estadistica.cargarJugadores(tb);
                jTextField1.setVisible(false);
                btnBuscar.setVisible(false);
                lblIcono.setVisible(false);
                jTable1.setModel(tb);
                break;
                
            case "Individual":
                lblTitulo.setText("ESTADISTICAS DEL JUEGO \"SERPIENTES Y ESCALERAS\" / PARTIDAS INDIVIDUALES");
                cargarColumnas(tb,individual);
                estadistica.cargarJuegosIndividuales(tb, null);
                jTable1.setModel(tb);
                break;
                
            case "Competencia":
                tbx = (DefaultTableModel)jTable1.getModel();
                lblDetalle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/detalle.png"))); 
                lblTitulo.setText("ESTADISTICAS DEL JUEGO \"SERPIENTES Y ESCALERAS\" / PARTIDAS DE COMPETENCIA");
                estadistica.cargarJuegosCompetitivo(tbx, null,lblDetalle);
                break;
                
            case "TOP3":
                lblTitulo.setText("ESTADISTICAS DEL JUEGO \"SERPIENTES Y ESCALERAS\" / TOP 3 JUGADORES COMPETENCIA");
                cargarColumnas(tb,top3);
                estadistica.cargarMejoresCompetencia(tb);
                jTextField1.setVisible(false);
                btnBuscar.setVisible(false);
                lblIcono.setVisible(false);
                jTable1.setModel(tb);
                break;
                
            default:
                System.out.println("Opcion no disponible");
                break;
        }
        } catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"Error al cargar los datos","Error",3);
            System.out.println("Mensaje de error: " + ex);
        }
        
        
    }
    
    private final JLabel lblDetalle = new javax.swing.JLabel();
    DefaultTableModel tb = new DefaultTableModel();
    Estadistica estadistica = new Estadistica();
    DefaultTableModel tbx;
    private String modalidad;
    
    String[] jugador = {"Nickname","Nombre","Edad","Genero","Partidas individuales","Partidas competencia","Victorias","Derrotas"};
    String[] individual = {"Inicio Partida","Fin Partida","Nombre","Nickname","Ficha","Tablero","Cantidad Tiros","Numero Escaleras","Numero Serpientes"};
    String[] top3 = {"Posicion","Nombre","Nickname","Genero","Edad","Victorias"};
    
    private void cargarColumnas(DefaultTableModel tb,String[] columnas){
        for (int i = 0; i < columnas.length; i++) {
            tb.addColumn(columnas[i]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new RSMaterialComponent.RSTableMetro();
        rSButtonShapeIcon1 = new RSMaterialComponent.RSButtonShapeIcon();
        jPanel2 = new javax.swing.JPanel();
        btnBuscar = new RSMaterialComponent.RSButtonMaterialIconShadow();
        jTextField1 = new RSMaterialComponent.RSTextFieldTwo();
        lblIcono = new necesario.LabelIcon();
        jSeparator1 = new javax.swing.JSeparator();
        lblTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N° Partida", "Tablero", "Fecha inicio", "Fecha fin", "Jugador 1", "Contrincante", "Resultado", "Ganador", ""
            }
        ));
        jTable1.setBackgoundHead(new java.awt.Color(0, 102, 102));
        jTable1.setBackgoundHover(new java.awt.Color(0, 153, 153));
        jTable1.setColorPrimaryText(new java.awt.Color(0, 0, 0));
        jTable1.setColorSecondary(new java.awt.Color(0, 51, 153));
        jTable1.setColorSecundaryText(new java.awt.Color(255, 255, 255));
        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTable1.setFontHead(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jTable1.setFontRowHover(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTable1.setFontRowSelect(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTable1.setRowHeight(35);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(100);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(100);
            jTable1.getColumnModel().getColumn(4).setMinWidth(150);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(150);
            jTable1.getColumnModel().getColumn(4).setMaxWidth(150);
            jTable1.getColumnModel().getColumn(5).setMinWidth(150);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(150);
            jTable1.getColumnModel().getColumn(5).setMaxWidth(150);
            jTable1.getColumnModel().getColumn(6).setMinWidth(140);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(140);
            jTable1.getColumnModel().getColumn(6).setMaxWidth(140);
            jTable1.getColumnModel().getColumn(7).setMinWidth(160);
            jTable1.getColumnModel().getColumn(7).setPreferredWidth(160);
            jTable1.getColumnModel().getColumn(7).setMaxWidth(160);
            jTable1.getColumnModel().getColumn(8).setMinWidth(40);
            jTable1.getColumnModel().getColumn(8).setPreferredWidth(40);
            jTable1.getColumnModel().getColumn(8).setMaxWidth(40);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 1310, 460));

        rSButtonShapeIcon1.setBackground(new java.awt.Color(0, 102, 102));
        rSButtonShapeIcon1.setText("  Regresar al menu");
        rSButtonShapeIcon1.setBackgroundHover(new java.awt.Color(153, 153, 153));
        rSButtonShapeIcon1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rSButtonShapeIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ARROW_BACK);
        rSButtonShapeIcon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonShapeIcon1ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonShapeIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, -1, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnBuscar.setBackground(new java.awt.Color(0, 102, 102));
        btnBuscar.setText("  Buscar partidas");
        btnBuscar.setBackgroundHover(new java.awt.Color(0, 102, 102));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1.setBorderColor(new java.awt.Color(0, 102, 102));
        jTextField1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField1.setPhColor(new java.awt.Color(0, 0, 0));
        jTextField1.setPlaceholder("Ingrese el nickname del jugador 1");
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        lblIcono.setForeground(new java.awt.Color(51, 51, 51));
        lblIcono.setToolTipText("Ver perfil");
        lblIcono.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PERSON);
        lblIcono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconoMouseClicked(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTitulo.setText("ESTADISTICAS DEL JUEGO \"SERPIENTES Y ESCALERAS\"");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(lblTitulo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 823, Short.MAX_VALUE)
                        .addComponent(lblIcono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(489, 489, 489)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblIcono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 1350, 610));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/fondoEstadisticas.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonShapeIcon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonShapeIcon1ActionPerformed
        new MenuEstadistica().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rSButtonShapeIcon1ActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String jugador;
        if (jTextField1.getText().isEmpty()) {
            jugador = null;
        } else {
            jugador = jTextField1.getText();
        }
        try{
            switch(modalidad){
            case "Individual":
                estadistica.cargarJuegosIndividuales(tb, jugador);
                break;
                
            case "Competencia":
                estadistica.cargarJuegosCompetitivo(tbx, jugador, lblDetalle);
                break;
            }
        } catch(SQLException ex){
            System.out.println("Mensaje de error: "+ ex);
        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void lblIconoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconoMouseClicked
       
    }//GEN-LAST:event_lblIconoMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (jTable1.getSelectedColumn()  == 8) {
            int row = jTable1.getSelectedRow();
            int idPartida = Integer.parseInt(jTable1.getValueAt(row, 0).toString());
            try {
                estadistica.cargarJuegosCompetitivoDetalle(idPartida);
            } catch (SQLException ex) {
                System.out.println("Error al cargar detalle de partida competitiva!!!");
                System.out.println("Error: " + ex);
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        if (jTextField1.getText().length() < 2) {
            try {
                estadistica.cargarJuegosCompetitivo(tbx, null, lblDetalle);
            } catch (SQLException ex) {
            }
        }
    }//GEN-LAST:event_jTextField1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estadisticas(args[0]).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialIconShadow btnBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private RSMaterialComponent.RSTableMetro jTable1;
    private RSMaterialComponent.RSTextFieldTwo jTextField1;
    private necesario.LabelIcon lblIcono;
    private javax.swing.JLabel lblTitulo;
    private RSMaterialComponent.RSButtonShapeIcon rSButtonShapeIcon1;
    // End of variables declaration//GEN-END:variables
}
