/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Diego
 */
public class Fichas extends javax.swing.JFrame {

    /**
     * Creates new form Selecciones
     */
    public Fichas() {
        initComponents();
        this.setLocationRelativeTo(null);
        // Cargando las fichas 
        urlFicha1 = "/Recursos/ficha-purple-guy-visor.png";
        urlFicha2 = "/Recursos/ficha-jett-visor.png";
        urlFicha3 = "/Recursos/ficha-spiderman-visor.png";
        urlFicha4 = "/Recursos/ficha-sailormoon-visor.png";
    }

    String urlFicha1,urlFicha2,urlFicha3,urlFicha4;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rSPanelBorder2 = new RSMaterialComponent.RSPanelBorder();
        btnFicha1 = new RSMaterialComponent.RSButtonMaterialOne();
        jLabel3 = new javax.swing.JLabel();
        rSPanelBorder3 = new RSMaterialComponent.RSPanelBorder();
        btnFicha2 = new RSMaterialComponent.RSButtonMaterialOne();
        jLabel4 = new javax.swing.JLabel();
        rSPanelBorder4 = new RSMaterialComponent.RSPanelBorder();
        btnFicha3 = new RSMaterialComponent.RSButtonMaterialOne();
        jLabel6 = new javax.swing.JLabel();
        rSPanelBorder5 = new RSMaterialComponent.RSPanelBorder();
        btnFicha4 = new RSMaterialComponent.RSButtonMaterialOne();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        rSButtonShapeIcon1 = new RSMaterialComponent.RSButtonShapeIcon();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSPanelBorder2.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelBorder2.setWidthBorder(2);
        rSPanelBorder2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnFicha1.setBackground(new java.awt.Color(153, 0, 153));
        btnFicha1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnFicha1.setText("Ficha Purple Guy");
        btnFicha1.setBackgroundHover(new java.awt.Color(153, 153, 153));
        btnFicha1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnFicha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFicha1ActionPerformed(evt);
            }
        });
        rSPanelBorder2.add(btnFicha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 290, 70));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/ficha-purple-guy.png"))); // NOI18N
        rSPanelBorder2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 280, 290));

        jPanel1.add(rSPanelBorder2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 290, 360));

        rSPanelBorder3.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelBorder3.setWidthBorder(2);
        rSPanelBorder3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnFicha2.setBackground(new java.awt.Color(255, 204, 204));
        btnFicha2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnFicha2.setText("Ficha de Jett");
        btnFicha2.setBackgroundHover(new java.awt.Color(153, 153, 153));
        btnFicha2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnFicha2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFicha2ActionPerformed(evt);
            }
        });
        rSPanelBorder3.add(btnFicha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 290, 70));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/ficha-jett.png"))); // NOI18N
        rSPanelBorder3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 280, 290));

        jPanel1.add(rSPanelBorder3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 290, 360));

        rSPanelBorder4.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelBorder4.setWidthBorder(2);
        rSPanelBorder4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnFicha3.setBackground(new java.awt.Color(204, 0, 51));
        btnFicha3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnFicha3.setText("Ficha de Spiderman");
        btnFicha3.setBackgroundHover(new java.awt.Color(153, 153, 153));
        btnFicha3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnFicha3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFicha3ActionPerformed(evt);
            }
        });
        rSPanelBorder4.add(btnFicha3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 290, 70));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/ficha-spiderman.png"))); // NOI18N
        rSPanelBorder4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 280, 290));

        jPanel1.add(rSPanelBorder4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 170, 290, 360));

        rSPanelBorder5.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelBorder5.setWidthBorder(2);
        rSPanelBorder5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnFicha4.setBackground(new java.awt.Color(102, 204, 255));
        btnFicha4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnFicha4.setText("Ficha Sailor Moon");
        btnFicha4.setAutoscrolls(true);
        btnFicha4.setBackgroundHover(new java.awt.Color(153, 153, 153));
        btnFicha4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnFicha4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFicha4ActionPerformed(evt);
            }
        });
        rSPanelBorder5.add(btnFicha4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 290, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/ficha-sailormoon.png"))); // NOI18N
        rSPanelBorder5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 280, 290));

        jPanel1.add(rSPanelBorder5, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 170, 290, 360));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel5.setText("FICHAS DISPONIBLES");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, -1, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 420, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 1310, 650));

        rSButtonShapeIcon1.setBackground(new java.awt.Color(0, 153, 153));
        rSButtonShapeIcon1.setText("Regresar al menu");
        rSButtonShapeIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ARROW_BACK);
        rSButtonShapeIcon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonShapeIcon1ActionPerformed(evt);
            }
        });
        getContentPane().add(rSButtonShapeIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 190, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/fondoEstadisticas.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonShapeIcon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonShapeIcon1ActionPerformed
        MenuPrincipal a = new MenuPrincipal();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rSButtonShapeIcon1ActionPerformed

    private void btnFicha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFicha1ActionPerformed
        new VisorFicha(urlFicha1).setVisible(true);
    }//GEN-LAST:event_btnFicha1ActionPerformed

    private void btnFicha2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFicha2ActionPerformed
        new VisorFicha(urlFicha2).setVisible(true);
    }//GEN-LAST:event_btnFicha2ActionPerformed

    private void btnFicha3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFicha3ActionPerformed
        new VisorFicha(urlFicha3).setVisible(true);
    }//GEN-LAST:event_btnFicha3ActionPerformed

    private void btnFicha4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFicha4ActionPerformed
        new VisorFicha(urlFicha4).setVisible(true);
    }//GEN-LAST:event_btnFicha4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fichas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fichas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fichas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fichas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fichas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialOne btnFicha1;
    private RSMaterialComponent.RSButtonMaterialOne btnFicha2;
    private RSMaterialComponent.RSButtonMaterialOne btnFicha3;
    private RSMaterialComponent.RSButtonMaterialOne btnFicha4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private RSMaterialComponent.RSButtonShapeIcon rSButtonShapeIcon1;
    private RSMaterialComponent.RSPanelBorder rSPanelBorder2;
    private RSMaterialComponent.RSPanelBorder rSPanelBorder3;
    private RSMaterialComponent.RSPanelBorder rSPanelBorder4;
    private RSMaterialComponent.RSPanelBorder rSPanelBorder5;
    // End of variables declaration//GEN-END:variables
}
