/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Helpers.Funciones;
import Modelo.Jugador;
import javax.swing.JOptionPane;

/**
 *
 * @author Diego
 */
public class LoginCompetencia extends javax.swing.JFrame {

    /**
     * Creates new form Login
     *
     * @param modalidad
     */
    public LoginCompetencia(String modalidad) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.modalidad = modalidad;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    Jugador jugador = new Jugador();
    Funciones tool = new Funciones();
    private String modalidad;

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField1 = new necesario.TextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtClave1 = new RSMaterialComponent.RSPasswordMaterial();
        txtNickname1 = new RSMaterialComponent.RSTextFieldMaterial();
        txtNickname2 = new RSMaterialComponent.RSTextFieldMaterial();
        txtClave2 = new RSMaterialComponent.RSPasswordMaterial();
        lblRegisterCompetencia = new javax.swing.JLabel();
        btnIniciarSesionCompetencia = new RSMaterialComponent.RSButtonMaterialOne();
        btnRegresar1 = new RSMaterialComponent.RSButtonShapeIcon();
        jLabel3 = new javax.swing.JLabel();

        textField1.setText("textField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/login.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, 180));

        txtClave1.setForeground(new java.awt.Color(0, 0, 0));
        txtClave1.setColorMaterial(new java.awt.Color(0, 0, 0));
        txtClave1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtClave1.setPhColor(new java.awt.Color(0, 0, 0));
        txtClave1.setPlaceholder("Clave jugador 1");
        txtClave1.setSelectionColor(new java.awt.Color(0, 0, 0));
        jPanel2.add(txtClave1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 200, -1));

        txtNickname1.setForeground(new java.awt.Color(0, 0, 0));
        txtNickname1.setColorMaterial(new java.awt.Color(0, 0, 0));
        txtNickname1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtNickname1.setPhColor(new java.awt.Color(0, 0, 0));
        txtNickname1.setPlaceholder("Nickname del jugador 1");
        txtNickname1.setSelectionColor(new java.awt.Color(0, 0, 0));
        jPanel2.add(txtNickname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 200, -1));

        txtNickname2.setForeground(new java.awt.Color(0, 0, 0));
        txtNickname2.setColorMaterial(new java.awt.Color(0, 0, 0));
        txtNickname2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtNickname2.setPhColor(new java.awt.Color(0, 0, 0));
        txtNickname2.setPlaceholder("Nickname del jugador 2");
        txtNickname2.setSelectionColor(new java.awt.Color(0, 0, 0));
        jPanel2.add(txtNickname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 200, -1));

        txtClave2.setForeground(new java.awt.Color(0, 0, 0));
        txtClave2.setColorMaterial(new java.awt.Color(0, 0, 0));
        txtClave2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtClave2.setPhColor(new java.awt.Color(0, 0, 0));
        txtClave2.setPlaceholder("Clave jugador 2");
        txtClave2.setSelectionColor(new java.awt.Color(0, 0, 0));
        jPanel2.add(txtClave2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 200, -1));

        lblRegisterCompetencia.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblRegisterCompetencia.setText("No tienes registro dentro del juego?");
        lblRegisterCompetencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegisterCompetenciaMouseClicked(evt);
            }
        });
        jPanel2.add(lblRegisterCompetencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, 20));

        btnIniciarSesionCompetencia.setBackground(new java.awt.Color(0, 204, 153));
        btnIniciarSesionCompetencia.setText("Iniciar sesión ");
        btnIniciarSesionCompetencia.setBackgroundHover(new java.awt.Color(153, 153, 153));
        btnIniciarSesionCompetencia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnIniciarSesionCompetencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionCompetenciaActionPerformed(evt);
            }
        });
        jPanel2.add(btnIniciarSesionCompetencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 420, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 490, 410));

        btnRegresar1.setBackground(new java.awt.Color(0, 153, 153));
        btnRegresar1.setText("  Cambiar modalidad");
        btnRegresar1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ARROW_BACK);
        btnRegresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 153, 153));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/fondoLogin.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblRegisterCompetenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegisterCompetenciaMouseClicked
        new Register(this.modalidad).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblRegisterCompetenciaMouseClicked

    private void btnIniciarSesionCompetenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionCompetenciaActionPerformed
        Jugador.setClave(tool.encriptarClave(txtClave1.getText()));
        Jugador.setNickname(txtNickname1.getText());
        if (jugador.iniciarSesion()) {
            Jugador.setClave2(tool.encriptarClave(txtClave2.getText()));
            Jugador.setNickname2(txtNickname2.getText());
            if (jugador.iniciarSesionJugadorDos()) {
                JOptionPane.showMessageDialog(null, "Credenciales correctas", "Juego Competitivo", 1);
                new SeleccionTablero(modalidad).setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Credenciales del jugador 2 incorrectas ");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Credenciales del jugador 1 incorrectas");
        }
    }//GEN-LAST:event_btnIniciarSesionCompetenciaActionPerformed

    private void btnRegresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresar1ActionPerformed
        new Modalidad().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginCompetencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginCompetencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginCompetencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginCompetencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginCompetencia(args[0]).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialOne btnIniciarSesionCompetencia;
    private RSMaterialComponent.RSButtonShapeIcon btnRegresar1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblRegisterCompetencia;
    private necesario.TextField textField1;
    private RSMaterialComponent.RSPasswordMaterial txtClave1;
    private RSMaterialComponent.RSPasswordMaterial txtClave2;
    private RSMaterialComponent.RSTextFieldMaterial txtNickname1;
    private RSMaterialComponent.RSTextFieldMaterial txtNickname2;
    // End of variables declaration//GEN-END:variables
}
