/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Helpers.Funciones;
import Modelo.Jugador;
import javax.swing.JOptionPane;

/**
 *
 * @author Diego
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     *
     * @param modalidad
     */
    public Login(String modalidad) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.modalidad = modalidad;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    Jugador jugador = new Jugador();
    Funciones tool = new Funciones();
    private String modalidad;

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField1 = new necesario.TextField();
        jPanel1 = new javax.swing.JPanel();
        btnRegresar = new RSMaterialComponent.RSButtonShapeIcon();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtClave1 = new RSMaterialComponent.RSPasswordMaterial();
        lblRegisterIndividual = new javax.swing.JLabel();
        btnIniciarSesion = new RSMaterialComponent.RSButtonMaterialOne();
        txtNickname1 = new RSMaterialComponent.RSTextFieldMaterial();
        jLabel3 = new javax.swing.JLabel();

        textField1.setText("textField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegresar.setBackground(new java.awt.Color(0, 153, 153));
        btnRegresar.setText("  Cambiar modalidad");
        btnRegresar.setBackgroundHover(new java.awt.Color(153, 153, 153));
        btnRegresar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ARROW_BACK);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/login.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, 180));

        txtClave1.setForeground(new java.awt.Color(0, 0, 0));
        txtClave1.setColorMaterial(new java.awt.Color(0, 0, 0));
        txtClave1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtClave1.setPhColor(new java.awt.Color(0, 0, 0));
        txtClave1.setPlaceholder("Clave jugador");
        txtClave1.setSelectionColor(new java.awt.Color(0, 0, 0));
        jPanel2.add(txtClave1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 300, -1));

        lblRegisterIndividual.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRegisterIndividual.setText("No tienes registro dentro del juego?");
        lblRegisterIndividual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegisterIndividualMouseClicked(evt);
            }
        });
        jPanel2.add(lblRegisterIndividual, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, -1));

        btnIniciarSesion.setBackground(new java.awt.Color(0, 204, 153));
        btnIniciarSesion.setText("Iniciar sesión ");
        btnIniciarSesion.setBackgroundHover(new java.awt.Color(153, 153, 153));
        btnIniciarSesion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });
        jPanel2.add(btnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 330, -1));

        txtNickname1.setForeground(new java.awt.Color(0, 0, 0));
        txtNickname1.setColorMaterial(new java.awt.Color(0, 0, 0));
        txtNickname1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtNickname1.setPhColor(new java.awt.Color(0, 0, 0));
        txtNickname1.setPlaceholder("Nickname del jugador");
        jPanel2.add(txtNickname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 300, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 480, 410));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/fondoLogin.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        new Modalidad().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        Jugador.setClave(tool.encriptarClave(txtClave1.getText()));
        Jugador.setNickname(txtNickname1.getText());
        if (jugador.iniciarSesion()) {
            JOptionPane.showMessageDialog(null, "Credenciales correctas", "Juego Individual", 1);
            new SeleccionTablero(modalidad).setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Credenciales incorrectas");
        }
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void lblRegisterIndividualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegisterIndividualMouseClicked
        new Register(this.modalidad).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblRegisterIndividualMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login(args[0]).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialOne btnIniciarSesion;
    private RSMaterialComponent.RSButtonShapeIcon btnRegresar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblRegisterIndividual;
    private necesario.TextField textField1;
    private RSMaterialComponent.RSPasswordMaterial txtClave1;
    private RSMaterialComponent.RSTextFieldMaterial txtNickname1;
    // End of variables declaration//GEN-END:variables
}
