/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
/**
 *
 * @author Diego
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */   
    public MenuPrincipal() {
        initComponents();    
        this.setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPartida = new newscomponents.RSButtonIcon_new();
        btnEstadisticas = new newscomponents.RSButtonIcon_new();
        btnFicha = new newscomponents.RSButtonIcon_new();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rSButtonIcon_new1 = new newscomponents.RSButtonIcon_new();
        btnTablero = new newscomponents.RSButtonIcon_new();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPartida.setBackground(new java.awt.Color(0, 153, 153));
        btnPartida.setForeground(new java.awt.Color(0, 0, 0));
        btnPartida.setText("       Nueva partida");
        btnPartida.setBackgroundHover(new java.awt.Color(204, 204, 204));
        btnPartida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPartida.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnPartida.setIcons(null);
        btnPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPartidaActionPerformed(evt);
            }
        });
        jPanel1.add(btnPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 300, 60));

        btnEstadisticas.setBackground(new java.awt.Color(0, 153, 153));
        btnEstadisticas.setForeground(new java.awt.Color(0, 0, 0));
        btnEstadisticas.setText("         Estadisticas");
        btnEstadisticas.setBackgroundHover(new java.awt.Color(204, 204, 204));
        btnEstadisticas.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnEstadisticas.setIcons(null);
        btnEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadisticasActionPerformed(evt);
            }
        });
        jPanel1.add(btnEstadisticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 300, 60));

        btnFicha.setBackground(new java.awt.Color(0, 153, 153));
        btnFicha.setForeground(new java.awt.Color(0, 0, 0));
        btnFicha.setText("             Fichas");
        btnFicha.setBackgroundHover(new java.awt.Color(204, 204, 204));
        btnFicha.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnFicha.setIcons(null);
        btnFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFichaActionPerformed(evt);
            }
        });
        jPanel1.add(btnFicha, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 440, 300, 60));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 30)); // NOI18N
        jLabel1.setText("MENU PRINCIPAL");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, -1, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/logo.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -20, -1, 662));

        rSButtonIcon_new1.setBackground(new java.awt.Color(0, 153, 153));
        rSButtonIcon_new1.setForeground(new java.awt.Color(0, 0, 0));
        rSButtonIcon_new1.setText("       Salir del juego");
        rSButtonIcon_new1.setBackgroundHover(new java.awt.Color(204, 204, 204));
        rSButtonIcon_new1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rSButtonIcon_new1.setIcons(null);
        rSButtonIcon_new1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIcon_new1ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonIcon_new1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 590, 270, 50));

        btnTablero.setBackground(new java.awt.Color(0, 153, 153));
        btnTablero.setForeground(new java.awt.Color(0, 0, 0));
        btnTablero.setText("           Tableros");
        btnTablero.setBackgroundHover(new java.awt.Color(204, 204, 204));
        btnTablero.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnTablero.setIcons(null);
        btnTablero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTableroActionPerformed(evt);
            }
        });
        jPanel1.add(btnTablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, 300, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/fondoCasillaEspecial.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 690));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 340, 20));

        jButton1.setText("jButton1");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 300, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPartidaActionPerformed
        new Modalidad().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPartidaActionPerformed

    private void btnEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadisticasActionPerformed
        new MenuEstadistica().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEstadisticasActionPerformed

    private void btnFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFichaActionPerformed
        new Fichas().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnFichaActionPerformed

    private void btnTableroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTableroActionPerformed
        new Tableros().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTableroActionPerformed

    private void rSButtonIcon_new1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIcon_new1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_rSButtonIcon_new1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private newscomponents.RSButtonIcon_new btnEstadisticas;
    private newscomponents.RSButtonIcon_new btnFicha;
    private newscomponents.RSButtonIcon_new btnPartida;
    private newscomponents.RSButtonIcon_new btnTablero;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private newscomponents.RSButtonIcon_new rSButtonIcon_new1;
    // End of variables declaration//GEN-END:variables
}
