/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Helpers.Funciones;
import Modelo.Juego;

/**
 *
 * @author Diego
 */
public class SeleccionTablero extends javax.swing.JFrame {

    /**
     * Creates new form Selecciones
     * @param modalidad
     */
    public SeleccionTablero(String modalidad) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.modalidad = modalidad;
    }
    
    private String modalidad;
    Funciones obj = new Funciones();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        rSPanelBorder1 = new RSMaterialComponent.RSPanelBorder();
        btnDificil = new RSMaterialComponent.RSButtonMaterialOne();
        lblTablero1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        rSPanelBorder4 = new RSMaterialComponent.RSPanelBorder();
        btnFacil = new RSMaterialComponent.RSButtonMaterialOne();
        lblTablero4 = new javax.swing.JLabel();
        rSPanelBorder5 = new RSMaterialComponent.RSPanelBorder();
        btnIntermedio = new RSMaterialComponent.RSButtonMaterialOne();
        lblTablero5 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel186 = new javax.swing.JLabel();
        jLabel187 = new javax.swing.JLabel();
        jLabel188 = new javax.swing.JLabel();
        jLabel189 = new javax.swing.JLabel();
        jLabel190 = new javax.swing.JLabel();
        jLabel191 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel192 = new javax.swing.JLabel();
        jLabel193 = new javax.swing.JLabel();
        jLabel194 = new javax.swing.JLabel();
        jLabel195 = new javax.swing.JLabel();
        jLabel196 = new javax.swing.JLabel();
        jLabel197 = new javax.swing.JLabel();
        jLabel198 = new javax.swing.JLabel();
        jLabel199 = new javax.swing.JLabel();
        jLabel200 = new javax.swing.JLabel();
        jLabel201 = new javax.swing.JLabel();
        jLabel202 = new javax.swing.JLabel();
        jLabel203 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jLabel204 = new javax.swing.JLabel();
        jLabel205 = new javax.swing.JLabel();
        jLabel206 = new javax.swing.JLabel();
        jLabel207 = new javax.swing.JLabel();
        jLabel208 = new javax.swing.JLabel();
        jLabel209 = new javax.swing.JLabel();
        jLabel210 = new javax.swing.JLabel();
        jLabel211 = new javax.swing.JLabel();
        jLabel212 = new javax.swing.JLabel();
        jLabel213 = new javax.swing.JLabel();
        jLabel214 = new javax.swing.JLabel();
        jLabel215 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jLabel216 = new javax.swing.JLabel();
        jLabel217 = new javax.swing.JLabel();
        jLabel218 = new javax.swing.JLabel();
        jLabel219 = new javax.swing.JLabel();
        jLabel220 = new javax.swing.JLabel();
        jLabel221 = new javax.swing.JLabel();
        jLabel222 = new javax.swing.JLabel();
        jLabel223 = new javax.swing.JLabel();
        jLabel224 = new javax.swing.JLabel();
        jLabel225 = new javax.swing.JLabel();
        jLabel226 = new javax.swing.JLabel();
        jLabel227 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jLabel228 = new javax.swing.JLabel();
        jLabel229 = new javax.swing.JLabel();
        jLabel230 = new javax.swing.JLabel();
        jLabel231 = new javax.swing.JLabel();
        jLabel232 = new javax.swing.JLabel();
        jLabel233 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jLabel234 = new javax.swing.JLabel();
        jLabel235 = new javax.swing.JLabel();
        jLabel236 = new javax.swing.JLabel();
        jLabel237 = new javax.swing.JLabel();
        jLabel238 = new javax.swing.JLabel();
        jLabel239 = new javax.swing.JLabel();
        jLabel240 = new javax.swing.JLabel();
        jLabel241 = new javax.swing.JLabel();
        jLabel242 = new javax.swing.JLabel();
        jLabel243 = new javax.swing.JLabel();
        jLabel244 = new javax.swing.JLabel();
        jLabel245 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jLabel246 = new javax.swing.JLabel();
        jLabel247 = new javax.swing.JLabel();
        jLabel248 = new javax.swing.JLabel();
        jLabel249 = new javax.swing.JLabel();
        jLabel250 = new javax.swing.JLabel();
        jLabel251 = new javax.swing.JLabel();
        jLabel252 = new javax.swing.JLabel();
        jLabel253 = new javax.swing.JLabel();
        jLabel254 = new javax.swing.JLabel();
        jLabel255 = new javax.swing.JLabel();
        jLabel256 = new javax.swing.JLabel();
        jLabel257 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        jLabel258 = new javax.swing.JLabel();
        jLabel259 = new javax.swing.JLabel();
        jLabel260 = new javax.swing.JLabel();
        jLabel261 = new javax.swing.JLabel();
        jLabel262 = new javax.swing.JLabel();
        jLabel263 = new javax.swing.JLabel();
        jLabel264 = new javax.swing.JLabel();
        jLabel265 = new javax.swing.JLabel();
        jLabel266 = new javax.swing.JLabel();
        jLabel267 = new javax.swing.JLabel();
        jLabel268 = new javax.swing.JLabel();
        jLabel269 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel102 = new javax.swing.JLabel();
        jLabel103 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        jLabel106 = new javax.swing.JLabel();
        jLabel107 = new javax.swing.JLabel();
        jLabel109 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel124 = new javax.swing.JLabel();
        jLabel125 = new javax.swing.JLabel();
        jLabel126 = new javax.swing.JLabel();
        jLabel127 = new javax.swing.JLabel();
        jLabel128 = new javax.swing.JLabel();
        jLabel129 = new javax.swing.JLabel();
        jLabel130 = new javax.swing.JLabel();
        jLabel131 = new javax.swing.JLabel();
        jLabel132 = new javax.swing.JLabel();
        jLabel133 = new javax.swing.JLabel();
        jLabel134 = new javax.swing.JLabel();
        jLabel135 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel136 = new javax.swing.JLabel();
        jLabel137 = new javax.swing.JLabel();
        jLabel138 = new javax.swing.JLabel();
        jLabel139 = new javax.swing.JLabel();
        jLabel140 = new javax.swing.JLabel();
        jLabel141 = new javax.swing.JLabel();
        jLabel142 = new javax.swing.JLabel();
        jLabel143 = new javax.swing.JLabel();
        jLabel144 = new javax.swing.JLabel();
        jLabel145 = new javax.swing.JLabel();
        jLabel146 = new javax.swing.JLabel();
        jLabel147 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel104 = new javax.swing.JLabel();
        jLabel108 = new javax.swing.JLabel();
        jLabel110 = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        jLabel148 = new javax.swing.JLabel();
        jLabel149 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel150 = new javax.swing.JLabel();
        jLabel151 = new javax.swing.JLabel();
        jLabel152 = new javax.swing.JLabel();
        jLabel153 = new javax.swing.JLabel();
        jLabel154 = new javax.swing.JLabel();
        jLabel155 = new javax.swing.JLabel();
        jLabel156 = new javax.swing.JLabel();
        jLabel157 = new javax.swing.JLabel();
        jLabel158 = new javax.swing.JLabel();
        jLabel159 = new javax.swing.JLabel();
        jLabel160 = new javax.swing.JLabel();
        jLabel161 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel162 = new javax.swing.JLabel();
        jLabel163 = new javax.swing.JLabel();
        jLabel164 = new javax.swing.JLabel();
        jLabel165 = new javax.swing.JLabel();
        jLabel166 = new javax.swing.JLabel();
        jLabel167 = new javax.swing.JLabel();
        jLabel168 = new javax.swing.JLabel();
        jLabel169 = new javax.swing.JLabel();
        jLabel170 = new javax.swing.JLabel();
        jLabel171 = new javax.swing.JLabel();
        jLabel172 = new javax.swing.JLabel();
        jLabel173 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel174 = new javax.swing.JLabel();
        jLabel175 = new javax.swing.JLabel();
        jLabel176 = new javax.swing.JLabel();
        jLabel177 = new javax.swing.JLabel();
        jLabel178 = new javax.swing.JLabel();
        jLabel179 = new javax.swing.JLabel();
        jLabel180 = new javax.swing.JLabel();
        jLabel181 = new javax.swing.JLabel();
        jLabel182 = new javax.swing.JLabel();
        jLabel183 = new javax.swing.JLabel();
        jLabel184 = new javax.swing.JLabel();
        jLabel185 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel112 = new javax.swing.JLabel();
        jLabel113 = new javax.swing.JLabel();
        jLabel114 = new javax.swing.JLabel();
        jLabel115 = new javax.swing.JLabel();
        jLabel116 = new javax.swing.JLabel();
        jLabel117 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jLabel270 = new javax.swing.JLabel();
        jLabel271 = new javax.swing.JLabel();
        jLabel272 = new javax.swing.JLabel();
        jLabel273 = new javax.swing.JLabel();
        jLabel274 = new javax.swing.JLabel();
        jLabel275 = new javax.swing.JLabel();
        jLabel276 = new javax.swing.JLabel();
        jLabel277 = new javax.swing.JLabel();
        jLabel278 = new javax.swing.JLabel();
        jLabel279 = new javax.swing.JLabel();
        jLabel280 = new javax.swing.JLabel();
        jLabel281 = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        jLabel282 = new javax.swing.JLabel();
        jLabel283 = new javax.swing.JLabel();
        jLabel284 = new javax.swing.JLabel();
        jLabel285 = new javax.swing.JLabel();
        jLabel286 = new javax.swing.JLabel();
        jLabel287 = new javax.swing.JLabel();
        jLabel288 = new javax.swing.JLabel();
        jLabel289 = new javax.swing.JLabel();
        jLabel290 = new javax.swing.JLabel();
        jLabel291 = new javax.swing.JLabel();
        jLabel292 = new javax.swing.JLabel();
        jLabel293 = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        jLabel118 = new javax.swing.JLabel();
        jLabel119 = new javax.swing.JLabel();
        jLabel120 = new javax.swing.JLabel();
        jLabel121 = new javax.swing.JLabel();
        jLabel294 = new javax.swing.JLabel();
        jLabel295 = new javax.swing.JLabel();
        jPanel31 = new javax.swing.JPanel();
        jLabel296 = new javax.swing.JLabel();
        jLabel297 = new javax.swing.JLabel();
        jLabel298 = new javax.swing.JLabel();
        jLabel299 = new javax.swing.JLabel();
        jLabel300 = new javax.swing.JLabel();
        jLabel301 = new javax.swing.JLabel();
        jLabel302 = new javax.swing.JLabel();
        jLabel303 = new javax.swing.JLabel();
        jLabel304 = new javax.swing.JLabel();
        jLabel305 = new javax.swing.JLabel();
        jLabel306 = new javax.swing.JLabel();
        jLabel307 = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        jLabel308 = new javax.swing.JLabel();
        jLabel309 = new javax.swing.JLabel();
        jLabel310 = new javax.swing.JLabel();
        jLabel311 = new javax.swing.JLabel();
        jLabel312 = new javax.swing.JLabel();
        jLabel313 = new javax.swing.JLabel();
        jLabel314 = new javax.swing.JLabel();
        jLabel315 = new javax.swing.JLabel();
        jLabel316 = new javax.swing.JLabel();
        jLabel317 = new javax.swing.JLabel();
        jLabel318 = new javax.swing.JLabel();
        jLabel319 = new javax.swing.JLabel();
        jPanel33 = new javax.swing.JPanel();
        jLabel320 = new javax.swing.JLabel();
        jLabel321 = new javax.swing.JLabel();
        jLabel322 = new javax.swing.JLabel();
        jLabel323 = new javax.swing.JLabel();
        jLabel324 = new javax.swing.JLabel();
        jLabel325 = new javax.swing.JLabel();
        jLabel326 = new javax.swing.JLabel();
        jLabel327 = new javax.swing.JLabel();
        jLabel328 = new javax.swing.JLabel();
        jLabel329 = new javax.swing.JLabel();
        jLabel330 = new javax.swing.JLabel();
        jLabel331 = new javax.swing.JLabel();
        rSButtonShapeIcon1 = new RSMaterialComponent.RSButtonShapeIcon();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSPanelBorder1.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelBorder1.setWidthBorder(2);
        rSPanelBorder1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDificil.setBackground(new java.awt.Color(153, 0, 153));
        btnDificil.setText("Dificil");
        btnDificil.setBackgroundHover(new java.awt.Color(153, 153, 153));
        btnDificil.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDificil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDificilActionPerformed(evt);
            }
        });
        rSPanelBorder1.add(btnDificil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 260, 50));

        lblTablero1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/tablero mini hard.png"))); // NOI18N
        rSPanelBorder1.add(lblTablero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 350, 250));

        jPanel2.add(rSPanelBorder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 260, 300));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setText("Seleccione la dificultad en la que desea jugar");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 470, 40));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 80, 590, 6));

        rSPanelBorder4.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelBorder4.setWidthBorder(2);
        rSPanelBorder4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnFacil.setBackground(new java.awt.Color(0, 204, 102));
        btnFacil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btnFacil.setText("Facil");
        btnFacil.setBackgroundHover(new java.awt.Color(153, 153, 153));
        btnFacil.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnFacil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacilActionPerformed(evt);
            }
        });
        rSPanelBorder4.add(btnFacil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 250, 50));

        lblTablero4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/tablero mini easy (1).png"))); // NOI18N
        rSPanelBorder4.add(lblTablero4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 300, 270));

        jPanel2.add(rSPanelBorder4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 250, 300));

        rSPanelBorder5.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelBorder5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        rSPanelBorder5.setWidthBorder(2);
        rSPanelBorder5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIntermedio.setBackground(new java.awt.Color(0, 153, 153));
        btnIntermedio.setText("Intermedio");
        btnIntermedio.setBackgroundHover(new java.awt.Color(153, 153, 153));
        btnIntermedio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnIntermedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntermedioActionPerformed(evt);
            }
        });
        rSPanelBorder5.add(btnIntermedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 260, 50));

        lblTablero5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/tablero mini medium.png"))); // NOI18N
        rSPanelBorder5.add(lblTablero5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 300, 260));

        jPanel2.add(rSPanelBorder5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 260, 300));

        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel186.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel186.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel186.setText("  Serpientes");
        jPanel20.add(jLabel186, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel187.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel187.setText("9");
        jPanel20.add(jLabel187, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 50, 30));

        jLabel188.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel188.setText("3");
        jPanel20.add(jLabel188, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 30));

        jLabel189.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel189.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel189.setText("  Casillas");
        jPanel20.add(jLabel189, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel190.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel190.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel190.setText("   Escaleras");
        jPanel20.add(jLabel190, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 70, 120, -1));

        jLabel191.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel191.setText("40");
        jPanel20.add(jLabel191, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 50, 30));

        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel192.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel192.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel192.setText("Escaleras");
        jPanel21.add(jLabel192, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel193.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel193.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel193.setText(" Casillas");
        jPanel21.add(jLabel193, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel194.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel194.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel194.setText(" Serpientes");
        jPanel21.add(jLabel194, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel195.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel195.setText("3");
        jPanel21.add(jLabel195, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, 20));

        jLabel196.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel196.setText("24");
        jPanel21.add(jLabel196, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 20));

        jLabel197.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel197.setText("5");
        jPanel21.add(jLabel197, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 20));

        jLabel198.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel198.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel198.setText(" Casillas");
        jPanel21.add(jLabel198, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel199.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel199.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel199.setText("Escaleras");
        jPanel21.add(jLabel199, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel200.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel200.setText("5");
        jPanel21.add(jLabel200, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 20));

        jLabel201.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel201.setText("24");
        jPanel21.add(jLabel201, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 20));

        jLabel202.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel202.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel202.setText(" Serpientes");
        jPanel21.add(jLabel202, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel203.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel203.setText("3");
        jPanel21.add(jLabel203, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, 20));

        jPanel20.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 400, 130));

        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel204.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel204.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel204.setText("Escaleras");
        jPanel22.add(jLabel204, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel205.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel205.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel205.setText(" Casillas");
        jPanel22.add(jLabel205, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel206.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel206.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel206.setText(" Serpientes");
        jPanel22.add(jLabel206, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel207.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel207.setText("3");
        jPanel22.add(jLabel207, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, 20));

        jLabel208.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel208.setText("24");
        jPanel22.add(jLabel208, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 20));

        jLabel209.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel209.setText("5");
        jPanel22.add(jLabel209, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 20));

        jLabel210.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel210.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel210.setText(" Casillas");
        jPanel22.add(jLabel210, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel211.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel211.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel211.setText("Escaleras");
        jPanel22.add(jLabel211, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel212.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel212.setText("5");
        jPanel22.add(jLabel212, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 20));

        jLabel213.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel213.setText("24");
        jPanel22.add(jLabel213, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 20));

        jLabel214.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel214.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel214.setText(" Serpientes");
        jPanel22.add(jLabel214, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel215.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel215.setText("3");
        jPanel22.add(jLabel215, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, 20));

        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel216.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel216.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel216.setText("Escaleras");
        jPanel23.add(jLabel216, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel217.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel217.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel217.setText(" Casillas");
        jPanel23.add(jLabel217, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel218.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel218.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel218.setText(" Serpientes");
        jPanel23.add(jLabel218, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel219.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel219.setText("3");
        jPanel23.add(jLabel219, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, 20));

        jLabel220.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel220.setText("24");
        jPanel23.add(jLabel220, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 20));

        jLabel221.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel221.setText("5");
        jPanel23.add(jLabel221, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 20));

        jLabel222.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel222.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel222.setText(" Casillas");
        jPanel23.add(jLabel222, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel223.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel223.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel223.setText("Escaleras");
        jPanel23.add(jLabel223, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel224.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel224.setText("5");
        jPanel23.add(jLabel224, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 20));

        jLabel225.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel225.setText("24");
        jPanel23.add(jLabel225, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 20));

        jLabel226.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel226.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel226.setText(" Serpientes");
        jPanel23.add(jLabel226, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel227.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel227.setText("3");
        jPanel23.add(jLabel227, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, 20));

        jPanel22.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 400, 130));

        jPanel20.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 400, 130));

        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel228.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel228.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel228.setText("  Serpientes");
        jPanel24.add(jLabel228, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel229.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel229.setText("3");
        jPanel24.add(jLabel229, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 50, 30));

        jLabel230.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel230.setText("5");
        jPanel24.add(jLabel230, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 30));

        jLabel231.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel231.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel231.setText("  Casillas");
        jPanel24.add(jLabel231, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel232.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel232.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel232.setText("   Escaleras");
        jPanel24.add(jLabel232, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 70, 120, -1));

        jLabel233.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel233.setText("24");
        jPanel24.add(jLabel233, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 50, 30));

        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel234.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel234.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel234.setText("Escaleras");
        jPanel25.add(jLabel234, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel235.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel235.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel235.setText(" Casillas");
        jPanel25.add(jLabel235, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel236.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel236.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel236.setText(" Serpientes");
        jPanel25.add(jLabel236, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel237.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel237.setText("3");
        jPanel25.add(jLabel237, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, 20));

        jLabel238.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel238.setText("24");
        jPanel25.add(jLabel238, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 20));

        jLabel239.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel239.setText("5");
        jPanel25.add(jLabel239, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 20));

        jLabel240.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel240.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel240.setText(" Casillas");
        jPanel25.add(jLabel240, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel241.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel241.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel241.setText("Escaleras");
        jPanel25.add(jLabel241, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel242.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel242.setText("5");
        jPanel25.add(jLabel242, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 20));

        jLabel243.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel243.setText("24");
        jPanel25.add(jLabel243, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 20));

        jLabel244.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel244.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel244.setText(" Serpientes");
        jPanel25.add(jLabel244, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel245.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel245.setText("3");
        jPanel25.add(jLabel245, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, 20));

        jPanel24.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 400, 130));

        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel246.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel246.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel246.setText("Escaleras");
        jPanel26.add(jLabel246, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel247.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel247.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel247.setText(" Casillas");
        jPanel26.add(jLabel247, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel248.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel248.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel248.setText(" Serpientes");
        jPanel26.add(jLabel248, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel249.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel249.setText("3");
        jPanel26.add(jLabel249, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, 20));

        jLabel250.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel250.setText("24");
        jPanel26.add(jLabel250, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 20));

        jLabel251.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel251.setText("5");
        jPanel26.add(jLabel251, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 20));

        jLabel252.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel252.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel252.setText(" Casillas");
        jPanel26.add(jLabel252, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel253.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel253.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel253.setText("Escaleras");
        jPanel26.add(jLabel253, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel254.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel254.setText("5");
        jPanel26.add(jLabel254, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 20));

        jLabel255.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel255.setText("24");
        jPanel26.add(jLabel255, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 20));

        jLabel256.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel256.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel256.setText(" Serpientes");
        jPanel26.add(jLabel256, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel257.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel257.setText("3");
        jPanel26.add(jLabel257, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, 20));

        jPanel27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel258.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel258.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel258.setText("Escaleras");
        jPanel27.add(jLabel258, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel259.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel259.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel259.setText(" Casillas");
        jPanel27.add(jLabel259, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel260.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel260.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel260.setText(" Serpientes");
        jPanel27.add(jLabel260, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel261.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel261.setText("3");
        jPanel27.add(jLabel261, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, 20));

        jLabel262.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel262.setText("24");
        jPanel27.add(jLabel262, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 20));

        jLabel263.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel263.setText("5");
        jPanel27.add(jLabel263, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 20));

        jLabel264.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel264.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel264.setText(" Casillas");
        jPanel27.add(jLabel264, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel265.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel265.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel265.setText("Escaleras");
        jPanel27.add(jLabel265, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel266.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel266.setText("5");
        jPanel27.add(jLabel266, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 20));

        jLabel267.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel267.setText("24");
        jPanel27.add(jLabel267, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 20));

        jLabel268.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel268.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel268.setText(" Serpientes");
        jPanel27.add(jLabel268, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel269.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel269.setText("3");
        jPanel27.add(jLabel269, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, 20));

        jPanel26.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 400, 130));

        jPanel24.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 400, 130));

        jPanel20.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 250, 190));

        jPanel2.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 420, 260, 190));

        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel102.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel102.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel102.setText("  Serpientes");
        jPanel12.add(jLabel102, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel103.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel103.setText("5");
        jPanel12.add(jLabel103, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 50, 30));

        jLabel105.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel105.setText("4");
        jPanel12.add(jLabel105, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 30));

        jLabel106.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel106.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel106.setText("  Casillas");
        jPanel12.add(jLabel106, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel107.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel107.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel107.setText("   Escaleras");
        jPanel12.add(jLabel107, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 70, 120, -1));

        jLabel109.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel109.setText("32");
        jPanel12.add(jLabel109, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 50, 30));

        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel124.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel124.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel124.setText("Escaleras");
        jPanel14.add(jLabel124, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel125.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel125.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel125.setText(" Casillas");
        jPanel14.add(jLabel125, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel126.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel126.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel126.setText(" Serpientes");
        jPanel14.add(jLabel126, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel127.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel127.setText("3");
        jPanel14.add(jLabel127, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, 20));

        jLabel128.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel128.setText("24");
        jPanel14.add(jLabel128, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 20));

        jLabel129.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel129.setText("5");
        jPanel14.add(jLabel129, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 20));

        jLabel130.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel130.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel130.setText(" Casillas");
        jPanel14.add(jLabel130, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel131.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel131.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel131.setText("Escaleras");
        jPanel14.add(jLabel131, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel132.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel132.setText("5");
        jPanel14.add(jLabel132, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 20));

        jLabel133.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel133.setText("24");
        jPanel14.add(jLabel133, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 20));

        jLabel134.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel134.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel134.setText(" Serpientes");
        jPanel14.add(jLabel134, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel135.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel135.setText("3");
        jPanel14.add(jLabel135, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, 20));

        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel136.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel136.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel136.setText("Escaleras");
        jPanel15.add(jLabel136, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel137.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel137.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel137.setText(" Casillas");
        jPanel15.add(jLabel137, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel138.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel138.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel138.setText(" Serpientes");
        jPanel15.add(jLabel138, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel139.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel139.setText("3");
        jPanel15.add(jLabel139, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, 20));

        jLabel140.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel140.setText("24");
        jPanel15.add(jLabel140, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 20));

        jLabel141.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel141.setText("5");
        jPanel15.add(jLabel141, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 20));

        jLabel142.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel142.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel142.setText(" Casillas");
        jPanel15.add(jLabel142, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel143.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel143.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel143.setText("Escaleras");
        jPanel15.add(jLabel143, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel144.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel144.setText("5");
        jPanel15.add(jLabel144, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 20));

        jLabel145.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel145.setText("24");
        jPanel15.add(jLabel145, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 20));

        jLabel146.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel146.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel146.setText(" Serpientes");
        jPanel15.add(jLabel146, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel147.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel147.setText("3");
        jPanel15.add(jLabel147, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, 20));

        jPanel14.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 400, 130));

        jPanel12.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 400, 130));

        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel104.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel104.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel104.setText("  Serpientes");
        jPanel16.add(jLabel104, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel108.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel108.setText("3");
        jPanel16.add(jLabel108, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 50, 30));

        jLabel110.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel110.setText("5");
        jPanel16.add(jLabel110, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 30));

        jLabel111.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel111.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel111.setText("  Casillas");
        jPanel16.add(jLabel111, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel148.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel148.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel148.setText("   Escaleras");
        jPanel16.add(jLabel148, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 70, 120, -1));

        jLabel149.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel149.setText("24");
        jPanel16.add(jLabel149, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 50, 30));

        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel150.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel150.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel150.setText("Escaleras");
        jPanel17.add(jLabel150, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel151.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel151.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel151.setText(" Casillas");
        jPanel17.add(jLabel151, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel152.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel152.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel152.setText(" Serpientes");
        jPanel17.add(jLabel152, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel153.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel153.setText("3");
        jPanel17.add(jLabel153, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, 20));

        jLabel154.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel154.setText("24");
        jPanel17.add(jLabel154, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 20));

        jLabel155.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel155.setText("5");
        jPanel17.add(jLabel155, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 20));

        jLabel156.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel156.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel156.setText(" Casillas");
        jPanel17.add(jLabel156, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel157.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel157.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel157.setText("Escaleras");
        jPanel17.add(jLabel157, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel158.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel158.setText("5");
        jPanel17.add(jLabel158, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 20));

        jLabel159.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel159.setText("24");
        jPanel17.add(jLabel159, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 20));

        jLabel160.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel160.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel160.setText(" Serpientes");
        jPanel17.add(jLabel160, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel161.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel161.setText("3");
        jPanel17.add(jLabel161, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, 20));

        jPanel16.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 400, 130));

        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel162.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel162.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel162.setText("Escaleras");
        jPanel18.add(jLabel162, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel163.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel163.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel163.setText(" Casillas");
        jPanel18.add(jLabel163, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel164.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel164.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel164.setText(" Serpientes");
        jPanel18.add(jLabel164, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel165.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel165.setText("3");
        jPanel18.add(jLabel165, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, 20));

        jLabel166.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel166.setText("24");
        jPanel18.add(jLabel166, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 20));

        jLabel167.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel167.setText("5");
        jPanel18.add(jLabel167, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 20));

        jLabel168.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel168.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel168.setText(" Casillas");
        jPanel18.add(jLabel168, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel169.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel169.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel169.setText("Escaleras");
        jPanel18.add(jLabel169, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel170.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel170.setText("5");
        jPanel18.add(jLabel170, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 20));

        jLabel171.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel171.setText("24");
        jPanel18.add(jLabel171, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 20));

        jLabel172.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel172.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel172.setText(" Serpientes");
        jPanel18.add(jLabel172, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel173.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel173.setText("3");
        jPanel18.add(jLabel173, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, 20));

        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel174.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel174.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel174.setText("Escaleras");
        jPanel19.add(jLabel174, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel175.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel175.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel175.setText(" Casillas");
        jPanel19.add(jLabel175, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel176.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel176.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel176.setText(" Serpientes");
        jPanel19.add(jLabel176, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel177.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel177.setText("3");
        jPanel19.add(jLabel177, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, 20));

        jLabel178.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel178.setText("24");
        jPanel19.add(jLabel178, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 20));

        jLabel179.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel179.setText("5");
        jPanel19.add(jLabel179, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 20));

        jLabel180.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel180.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel180.setText(" Casillas");
        jPanel19.add(jLabel180, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel181.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel181.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel181.setText("Escaleras");
        jPanel19.add(jLabel181, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel182.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel182.setText("5");
        jPanel19.add(jLabel182, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 20));

        jLabel183.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel183.setText("24");
        jPanel19.add(jLabel183, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 20));

        jLabel184.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel184.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel184.setText(" Serpientes");
        jPanel19.add(jLabel184, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel185.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel185.setText("3");
        jPanel19.add(jLabel185, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, 20));

        jPanel18.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 400, 130));

        jPanel16.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 400, 130));

        jPanel12.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 250, 190));

        jPanel2.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, 260, 190));

        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel112.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel112.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel112.setText("  Serpientes");
        jPanel13.add(jLabel112, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel113.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel113.setText("3");
        jPanel13.add(jLabel113, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 50, 30));

        jLabel114.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel114.setText("5");
        jPanel13.add(jLabel114, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 30));

        jLabel115.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel115.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel115.setText("  Casillas");
        jPanel13.add(jLabel115, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel116.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel116.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel116.setText("   Escaleras");
        jPanel13.add(jLabel116, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 70, 120, -1));

        jLabel117.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel117.setText("24");
        jPanel13.add(jLabel117, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 50, 30));

        jPanel28.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel270.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel270.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel270.setText("Escaleras");
        jPanel28.add(jLabel270, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel271.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel271.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel271.setText(" Casillas");
        jPanel28.add(jLabel271, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel272.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel272.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel272.setText(" Serpientes");
        jPanel28.add(jLabel272, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel273.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel273.setText("3");
        jPanel28.add(jLabel273, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, 20));

        jLabel274.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel274.setText("24");
        jPanel28.add(jLabel274, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 20));

        jLabel275.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel275.setText("5");
        jPanel28.add(jLabel275, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 20));

        jLabel276.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel276.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel276.setText(" Casillas");
        jPanel28.add(jLabel276, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel277.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel277.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel277.setText("Escaleras");
        jPanel28.add(jLabel277, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel278.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel278.setText("5");
        jPanel28.add(jLabel278, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 20));

        jLabel279.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel279.setText("24");
        jPanel28.add(jLabel279, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 20));

        jLabel280.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel280.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel280.setText(" Serpientes");
        jPanel28.add(jLabel280, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel281.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel281.setText("3");
        jPanel28.add(jLabel281, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, 20));

        jPanel29.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel282.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel282.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel282.setText("Escaleras");
        jPanel29.add(jLabel282, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel283.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel283.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel283.setText(" Casillas");
        jPanel29.add(jLabel283, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel284.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel284.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel284.setText(" Serpientes");
        jPanel29.add(jLabel284, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel285.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel285.setText("3");
        jPanel29.add(jLabel285, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, 20));

        jLabel286.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel286.setText("24");
        jPanel29.add(jLabel286, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 20));

        jLabel287.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel287.setText("5");
        jPanel29.add(jLabel287, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 20));

        jLabel288.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel288.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel288.setText(" Casillas");
        jPanel29.add(jLabel288, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel289.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel289.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel289.setText("Escaleras");
        jPanel29.add(jLabel289, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel290.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel290.setText("5");
        jPanel29.add(jLabel290, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 20));

        jLabel291.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel291.setText("24");
        jPanel29.add(jLabel291, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 20));

        jLabel292.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel292.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel292.setText(" Serpientes");
        jPanel29.add(jLabel292, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel293.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel293.setText("3");
        jPanel29.add(jLabel293, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, 20));

        jPanel28.add(jPanel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 400, 130));

        jPanel13.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 400, 130));

        jPanel30.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel118.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel118.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel118.setText("  Serpientes");
        jPanel30.add(jLabel118, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel119.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel119.setText("3");
        jPanel30.add(jLabel119, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 50, 30));

        jLabel120.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel120.setText("5");
        jPanel30.add(jLabel120, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 30));

        jLabel121.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel121.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel121.setText("  Casillas");
        jPanel30.add(jLabel121, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel294.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel294.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel294.setText("   Escaleras");
        jPanel30.add(jLabel294, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 70, 120, -1));

        jLabel295.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel295.setText("24");
        jPanel30.add(jLabel295, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 50, 30));

        jPanel31.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel296.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel296.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel296.setText("Escaleras");
        jPanel31.add(jLabel296, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel297.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel297.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel297.setText(" Casillas");
        jPanel31.add(jLabel297, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel298.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel298.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel298.setText(" Serpientes");
        jPanel31.add(jLabel298, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel299.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel299.setText("3");
        jPanel31.add(jLabel299, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, 20));

        jLabel300.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel300.setText("24");
        jPanel31.add(jLabel300, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 20));

        jLabel301.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel301.setText("5");
        jPanel31.add(jLabel301, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 20));

        jLabel302.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel302.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel302.setText(" Casillas");
        jPanel31.add(jLabel302, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel303.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel303.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel303.setText("Escaleras");
        jPanel31.add(jLabel303, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel304.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel304.setText("5");
        jPanel31.add(jLabel304, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 20));

        jLabel305.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel305.setText("24");
        jPanel31.add(jLabel305, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 20));

        jLabel306.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel306.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel306.setText(" Serpientes");
        jPanel31.add(jLabel306, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel307.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel307.setText("3");
        jPanel31.add(jLabel307, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, 20));

        jPanel30.add(jPanel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 400, 130));

        jPanel32.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel308.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel308.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel308.setText("Escaleras");
        jPanel32.add(jLabel308, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel309.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel309.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel309.setText(" Casillas");
        jPanel32.add(jLabel309, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel310.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel310.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel310.setText(" Serpientes");
        jPanel32.add(jLabel310, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel311.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel311.setText("3");
        jPanel32.add(jLabel311, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, 20));

        jLabel312.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel312.setText("24");
        jPanel32.add(jLabel312, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 20));

        jLabel313.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel313.setText("5");
        jPanel32.add(jLabel313, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 20));

        jLabel314.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel314.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel314.setText(" Casillas");
        jPanel32.add(jLabel314, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel315.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel315.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel315.setText("Escaleras");
        jPanel32.add(jLabel315, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel316.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel316.setText("5");
        jPanel32.add(jLabel316, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 20));

        jLabel317.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel317.setText("24");
        jPanel32.add(jLabel317, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 20));

        jLabel318.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel318.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel318.setText(" Serpientes");
        jPanel32.add(jLabel318, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel319.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel319.setText("3");
        jPanel32.add(jLabel319, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, 20));

        jPanel33.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel320.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel320.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel320.setText("Escaleras");
        jPanel33.add(jLabel320, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel321.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel321.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel321.setText(" Casillas");
        jPanel33.add(jLabel321, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel322.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel322.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel322.setText(" Serpientes");
        jPanel33.add(jLabel322, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel323.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel323.setText("3");
        jPanel33.add(jLabel323, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, 20));

        jLabel324.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel324.setText("24");
        jPanel33.add(jLabel324, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 20));

        jLabel325.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel325.setText("5");
        jPanel33.add(jLabel325, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 20));

        jLabel326.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel326.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel326.setText(" Casillas");
        jPanel33.add(jLabel326, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel327.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel327.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel327.setText("Escaleras");
        jPanel33.add(jLabel327, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel328.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel328.setText("5");
        jPanel33.add(jLabel328, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 20));

        jLabel329.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel329.setText("24");
        jPanel33.add(jLabel329, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 20));

        jLabel330.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel330.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel330.setText(" Serpientes");
        jPanel33.add(jLabel330, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel331.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel331.setText("3");
        jPanel33.add(jLabel331, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, 20));

        jPanel32.add(jPanel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 400, 130));

        jPanel30.add(jPanel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 400, 130));

        jPanel13.add(jPanel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 250, 190));

        jPanel2.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 250, 190));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 940, 640));

        rSButtonShapeIcon1.setBackground(new java.awt.Color(0, 153, 153));
        rSButtonShapeIcon1.setText("  Regresar al login");
        rSButtonShapeIcon1.setBackgroundHover(new java.awt.Color(153, 153, 153));
        rSButtonShapeIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ARROW_BACK);
        rSButtonShapeIcon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonShapeIcon1ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonShapeIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/fondoSelecciones.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDificilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDificilActionPerformed
        Juego.setIdTablero(3);
        Juego.setUrlTablero("/Recursos/tablero_dificil.jpg");
        new SeleccionFicha(modalidad,"1","").setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDificilActionPerformed

    private void rSButtonShapeIcon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonShapeIcon1ActionPerformed
        new MenuPrincipal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rSButtonShapeIcon1ActionPerformed

    private void btnFacilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacilActionPerformed
        Juego.setIdTablero(1);
        Juego.setUrlTablero("/Recursos/tablero_facil.jpg");
        new SeleccionFicha(modalidad,"1","").setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnFacilActionPerformed

    private void btnIntermedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntermedioActionPerformed
        Juego.setIdTablero(2);
        Juego.setUrlTablero("/Recursos/tablero_medio.jpg");
        new SeleccionFicha(modalidad,"1","").setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnIntermedioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeleccionTablero(args[0]).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialOne btnDificil;
    private RSMaterialComponent.RSButtonMaterialOne btnFacil;
    private RSMaterialComponent.RSButtonMaterialOne btnIntermedio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel132;
    private javax.swing.JLabel jLabel133;
    private javax.swing.JLabel jLabel134;
    private javax.swing.JLabel jLabel135;
    private javax.swing.JLabel jLabel136;
    private javax.swing.JLabel jLabel137;
    private javax.swing.JLabel jLabel138;
    private javax.swing.JLabel jLabel139;
    private javax.swing.JLabel jLabel140;
    private javax.swing.JLabel jLabel141;
    private javax.swing.JLabel jLabel142;
    private javax.swing.JLabel jLabel143;
    private javax.swing.JLabel jLabel144;
    private javax.swing.JLabel jLabel145;
    private javax.swing.JLabel jLabel146;
    private javax.swing.JLabel jLabel147;
    private javax.swing.JLabel jLabel148;
    private javax.swing.JLabel jLabel149;
    private javax.swing.JLabel jLabel150;
    private javax.swing.JLabel jLabel151;
    private javax.swing.JLabel jLabel152;
    private javax.swing.JLabel jLabel153;
    private javax.swing.JLabel jLabel154;
    private javax.swing.JLabel jLabel155;
    private javax.swing.JLabel jLabel156;
    private javax.swing.JLabel jLabel157;
    private javax.swing.JLabel jLabel158;
    private javax.swing.JLabel jLabel159;
    private javax.swing.JLabel jLabel160;
    private javax.swing.JLabel jLabel161;
    private javax.swing.JLabel jLabel162;
    private javax.swing.JLabel jLabel163;
    private javax.swing.JLabel jLabel164;
    private javax.swing.JLabel jLabel165;
    private javax.swing.JLabel jLabel166;
    private javax.swing.JLabel jLabel167;
    private javax.swing.JLabel jLabel168;
    private javax.swing.JLabel jLabel169;
    private javax.swing.JLabel jLabel170;
    private javax.swing.JLabel jLabel171;
    private javax.swing.JLabel jLabel172;
    private javax.swing.JLabel jLabel173;
    private javax.swing.JLabel jLabel174;
    private javax.swing.JLabel jLabel175;
    private javax.swing.JLabel jLabel176;
    private javax.swing.JLabel jLabel177;
    private javax.swing.JLabel jLabel178;
    private javax.swing.JLabel jLabel179;
    private javax.swing.JLabel jLabel180;
    private javax.swing.JLabel jLabel181;
    private javax.swing.JLabel jLabel182;
    private javax.swing.JLabel jLabel183;
    private javax.swing.JLabel jLabel184;
    private javax.swing.JLabel jLabel185;
    private javax.swing.JLabel jLabel186;
    private javax.swing.JLabel jLabel187;
    private javax.swing.JLabel jLabel188;
    private javax.swing.JLabel jLabel189;
    private javax.swing.JLabel jLabel190;
    private javax.swing.JLabel jLabel191;
    private javax.swing.JLabel jLabel192;
    private javax.swing.JLabel jLabel193;
    private javax.swing.JLabel jLabel194;
    private javax.swing.JLabel jLabel195;
    private javax.swing.JLabel jLabel196;
    private javax.swing.JLabel jLabel197;
    private javax.swing.JLabel jLabel198;
    private javax.swing.JLabel jLabel199;
    private javax.swing.JLabel jLabel200;
    private javax.swing.JLabel jLabel201;
    private javax.swing.JLabel jLabel202;
    private javax.swing.JLabel jLabel203;
    private javax.swing.JLabel jLabel204;
    private javax.swing.JLabel jLabel205;
    private javax.swing.JLabel jLabel206;
    private javax.swing.JLabel jLabel207;
    private javax.swing.JLabel jLabel208;
    private javax.swing.JLabel jLabel209;
    private javax.swing.JLabel jLabel210;
    private javax.swing.JLabel jLabel211;
    private javax.swing.JLabel jLabel212;
    private javax.swing.JLabel jLabel213;
    private javax.swing.JLabel jLabel214;
    private javax.swing.JLabel jLabel215;
    private javax.swing.JLabel jLabel216;
    private javax.swing.JLabel jLabel217;
    private javax.swing.JLabel jLabel218;
    private javax.swing.JLabel jLabel219;
    private javax.swing.JLabel jLabel220;
    private javax.swing.JLabel jLabel221;
    private javax.swing.JLabel jLabel222;
    private javax.swing.JLabel jLabel223;
    private javax.swing.JLabel jLabel224;
    private javax.swing.JLabel jLabel225;
    private javax.swing.JLabel jLabel226;
    private javax.swing.JLabel jLabel227;
    private javax.swing.JLabel jLabel228;
    private javax.swing.JLabel jLabel229;
    private javax.swing.JLabel jLabel230;
    private javax.swing.JLabel jLabel231;
    private javax.swing.JLabel jLabel232;
    private javax.swing.JLabel jLabel233;
    private javax.swing.JLabel jLabel234;
    private javax.swing.JLabel jLabel235;
    private javax.swing.JLabel jLabel236;
    private javax.swing.JLabel jLabel237;
    private javax.swing.JLabel jLabel238;
    private javax.swing.JLabel jLabel239;
    private javax.swing.JLabel jLabel240;
    private javax.swing.JLabel jLabel241;
    private javax.swing.JLabel jLabel242;
    private javax.swing.JLabel jLabel243;
    private javax.swing.JLabel jLabel244;
    private javax.swing.JLabel jLabel245;
    private javax.swing.JLabel jLabel246;
    private javax.swing.JLabel jLabel247;
    private javax.swing.JLabel jLabel248;
    private javax.swing.JLabel jLabel249;
    private javax.swing.JLabel jLabel250;
    private javax.swing.JLabel jLabel251;
    private javax.swing.JLabel jLabel252;
    private javax.swing.JLabel jLabel253;
    private javax.swing.JLabel jLabel254;
    private javax.swing.JLabel jLabel255;
    private javax.swing.JLabel jLabel256;
    private javax.swing.JLabel jLabel257;
    private javax.swing.JLabel jLabel258;
    private javax.swing.JLabel jLabel259;
    private javax.swing.JLabel jLabel260;
    private javax.swing.JLabel jLabel261;
    private javax.swing.JLabel jLabel262;
    private javax.swing.JLabel jLabel263;
    private javax.swing.JLabel jLabel264;
    private javax.swing.JLabel jLabel265;
    private javax.swing.JLabel jLabel266;
    private javax.swing.JLabel jLabel267;
    private javax.swing.JLabel jLabel268;
    private javax.swing.JLabel jLabel269;
    private javax.swing.JLabel jLabel270;
    private javax.swing.JLabel jLabel271;
    private javax.swing.JLabel jLabel272;
    private javax.swing.JLabel jLabel273;
    private javax.swing.JLabel jLabel274;
    private javax.swing.JLabel jLabel275;
    private javax.swing.JLabel jLabel276;
    private javax.swing.JLabel jLabel277;
    private javax.swing.JLabel jLabel278;
    private javax.swing.JLabel jLabel279;
    private javax.swing.JLabel jLabel280;
    private javax.swing.JLabel jLabel281;
    private javax.swing.JLabel jLabel282;
    private javax.swing.JLabel jLabel283;
    private javax.swing.JLabel jLabel284;
    private javax.swing.JLabel jLabel285;
    private javax.swing.JLabel jLabel286;
    private javax.swing.JLabel jLabel287;
    private javax.swing.JLabel jLabel288;
    private javax.swing.JLabel jLabel289;
    private javax.swing.JLabel jLabel290;
    private javax.swing.JLabel jLabel291;
    private javax.swing.JLabel jLabel292;
    private javax.swing.JLabel jLabel293;
    private javax.swing.JLabel jLabel294;
    private javax.swing.JLabel jLabel295;
    private javax.swing.JLabel jLabel296;
    private javax.swing.JLabel jLabel297;
    private javax.swing.JLabel jLabel298;
    private javax.swing.JLabel jLabel299;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel300;
    private javax.swing.JLabel jLabel301;
    private javax.swing.JLabel jLabel302;
    private javax.swing.JLabel jLabel303;
    private javax.swing.JLabel jLabel304;
    private javax.swing.JLabel jLabel305;
    private javax.swing.JLabel jLabel306;
    private javax.swing.JLabel jLabel307;
    private javax.swing.JLabel jLabel308;
    private javax.swing.JLabel jLabel309;
    private javax.swing.JLabel jLabel310;
    private javax.swing.JLabel jLabel311;
    private javax.swing.JLabel jLabel312;
    private javax.swing.JLabel jLabel313;
    private javax.swing.JLabel jLabel314;
    private javax.swing.JLabel jLabel315;
    private javax.swing.JLabel jLabel316;
    private javax.swing.JLabel jLabel317;
    private javax.swing.JLabel jLabel318;
    private javax.swing.JLabel jLabel319;
    private javax.swing.JLabel jLabel320;
    private javax.swing.JLabel jLabel321;
    private javax.swing.JLabel jLabel322;
    private javax.swing.JLabel jLabel323;
    private javax.swing.JLabel jLabel324;
    private javax.swing.JLabel jLabel325;
    private javax.swing.JLabel jLabel326;
    private javax.swing.JLabel jLabel327;
    private javax.swing.JLabel jLabel328;
    private javax.swing.JLabel jLabel329;
    private javax.swing.JLabel jLabel330;
    private javax.swing.JLabel jLabel331;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblTablero1;
    private javax.swing.JLabel lblTablero4;
    private javax.swing.JLabel lblTablero5;
    private RSMaterialComponent.RSButtonShapeIcon rSButtonShapeIcon1;
    private RSMaterialComponent.RSPanelBorder rSPanelBorder1;
    private RSMaterialComponent.RSPanelBorder rSPanelBorder4;
    private RSMaterialComponent.RSPanelBorder rSPanelBorder5;
    // End of variables declaration//GEN-END:variables
}
