/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Helpers.Funciones;
import Modelo.Juego;
import javax.swing.JOptionPane;

/**
 *
 * @author Diego
 */
public class SeleccionFicha extends javax.swing.JFrame {

    /**
     * Creates new form SeleccionFicha
     * @param modalidad
     * @param jugador
     * @param seleccion
     */
    public SeleccionFicha(String modalidad, String jugador,String seleccion) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.modalidad = modalidad;
        this.jugador = jugador;

        switch(modalidad){
            case "Individual":
                break;
                
            case "Competencia":
                if ("1".equals(jugador)) {
                    jLabel1.setText("Seleccione la ficha para el jugador 1");
                } else {
                    jLabel1.setText("Seleccione la ficha para el jugador 2");
                    switch(seleccion){
                        case "1":
                            rSPanelBorder1.setEnabled(false);
                            btnFicha1.setEnabled(false);
                            break;
                       
                        case "2":
                            rSPanelBorder2.setEnabled(false);
                            btnFicha2.setEnabled(false);
                            break;
                            
                        case "3":
                            rSPanelBorder3.setEnabled(false);
                            btnFicha3.setEnabled(false);
                            break;
                            
                        case "4":
                            rSPanelBorder3.setEnabled(false);
                            btnFicha4.setEnabled(false);
                            break;
                    }
                }
                break;
            default:
                JOptionPane.showMessageDialog(null, "Error no hay modalidad seleccionada","Seleccione modalidad", 2);
                new MenuPrincipal().setVisible(true);
                this.dispose();
                break;
        }
    }
    
    Funciones obj = new Funciones();
    private String modalidad;
    private String jugador;
    protected static String ficha1 ="",ficha2 ="";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        rSPanelBorder1 = new RSMaterialComponent.RSPanelBorder();
        btnFicha1 = new RSMaterialComponent.RSButtonMaterialOne();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        rSPanelBorder3 = new RSMaterialComponent.RSPanelBorder();
        btnFicha3 = new RSMaterialComponent.RSButtonMaterialOne();
        jLabel6 = new javax.swing.JLabel();
        rSPanelBorder4 = new RSMaterialComponent.RSPanelBorder();
        btnFicha4 = new RSMaterialComponent.RSButtonMaterialOne();
        jLabel2 = new javax.swing.JLabel();
        rSPanelBorder2 = new RSMaterialComponent.RSPanelBorder();
        btnFicha2 = new RSMaterialComponent.RSButtonMaterialOne();
        jLabel5 = new javax.swing.JLabel();
        rSButtonShapeIcon1 = new RSMaterialComponent.RSButtonShapeIcon();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSPanelBorder1.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelBorder1.setWidthBorder(2);
        rSPanelBorder1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnFicha1.setBackground(new java.awt.Color(153, 0, 153));
        btnFicha1.setText("Ficha Purple Guy");
        btnFicha1.setBackgroundHover(new java.awt.Color(153, 153, 153));
        btnFicha1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnFicha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFicha1ActionPerformed(evt);
            }
        });
        rSPanelBorder1.add(btnFicha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 270, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/ficha-purple-guy-selecciones.png"))); // NOI18N
        rSPanelBorder1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 230, 170));

        jPanel2.add(rSPanelBorder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 270, 210));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setText("Seleccione la ficha en la que desea jugar");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 420, 40));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 610, 10));

        rSPanelBorder3.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelBorder3.setWidthBorder(2);
        rSPanelBorder3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnFicha3.setBackground(new java.awt.Color(153, 0, 0));
        btnFicha3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnFicha3.setText("Ficha Spiderman");
        btnFicha3.setBackgroundHover(new java.awt.Color(153, 153, 153));
        btnFicha3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnFicha3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFicha3ActionPerformed(evt);
            }
        });
        rSPanelBorder3.add(btnFicha3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 270, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/ficha-spiderman-selecciones.png"))); // NOI18N
        rSPanelBorder3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 230, -1));

        jPanel2.add(rSPanelBorder3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 270, 210));

        rSPanelBorder4.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelBorder4.setWidthBorder(2);
        rSPanelBorder4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnFicha4.setBackground(new java.awt.Color(0, 204, 153));
        btnFicha4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnFicha4.setText("Ficha Sailor Moon");
        btnFicha4.setBackgroundHover(new java.awt.Color(153, 153, 153));
        btnFicha4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnFicha4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFicha4ActionPerformed(evt);
            }
        });
        rSPanelBorder4.add(btnFicha4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 270, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/ficha-sailormoon-selecciones.png"))); // NOI18N
        rSPanelBorder4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 230, -1));

        jPanel2.add(rSPanelBorder4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 270, 210));

        rSPanelBorder2.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelBorder2.setWidthBorder(2);
        rSPanelBorder2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnFicha2.setBackground(new java.awt.Color(255, 204, 204));
        btnFicha2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnFicha2.setText("Ficha Jett");
        btnFicha2.setBackgroundHover(new java.awt.Color(153, 153, 153));
        btnFicha2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnFicha2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFicha2ActionPerformed(evt);
            }
        });
        rSPanelBorder2.add(btnFicha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 270, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/ficha-jett-selecciones.png"))); // NOI18N
        rSPanelBorder2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 230, -1));

        jPanel2.add(rSPanelBorder2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 270, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 770, 530));

        rSButtonShapeIcon1.setBackground(new java.awt.Color(0, 153, 153));
        rSButtonShapeIcon1.setText("  Regresar al selector");
        rSButtonShapeIcon1.setBackgroundHover(new java.awt.Color(153, 153, 153));
        rSButtonShapeIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ARROW_BACK);
        rSButtonShapeIcon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonShapeIcon1ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonShapeIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 210, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/fondoSelecciones.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFicha2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFicha2ActionPerformed
        if (modalidad.equals("Individual")) {
            Juego.setUrlFichaJ1("/Recursos/ficha-jett-tablero.png");
            Juego.setIdFicha1(2);
            
            if (Juego.getUrlTablero().equals("/Recursos/tablero_dificil.jpg")) {
                new PartidaHard(this.modalidad, "jett").setVisible(true);
            } else {
                new Partida(this.modalidad, "jett").setVisible(true);
            }     
            
            this.dispose();
        } else {
            if (jugador.equals("1")) {
                Juego.setUrlFichaJ1("/Recursos/ficha-jett-tablero.png");
                ficha1 = "jett";
                Juego.setIdFicha1(2);
                new SeleccionFicha("Competencia","2","2").setVisible(true);
                this.dispose();
            } else {
                Juego.setUrlFichaJ2("/Recursos/ficha-jett-tablero.png");
                ficha2 = "jett";
                Juego.setIdFicha2(2);     
                if (Juego.getUrlTablero().equals("/Recursos/tablero_dificil.jpg")) {
                    new PartidaCompetenciaHard(this.modalidad,ficha1,ficha2).setVisible(true);
                } else {
                    new PartidaCompetencia(this.modalidad,ficha1,ficha2).setVisible(true);
                }          
                this.dispose();
            }
        }
    }//GEN-LAST:event_btnFicha2ActionPerformed

    private void btnFicha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFicha1ActionPerformed
        if (modalidad.equals("Individual")) {
            Juego.setUrlFichaJ1("/Recursos/ficha-purple-guy-tablero.png");
            Juego.setIdFicha1(1);
            if (Juego.getUrlTablero().equals("/Recursos/tablero_dificil.jpg")) {
                new PartidaHard(this.modalidad, "purple-guy").setVisible(true);
            } else {
                new Partida(this.modalidad, "purple-guy").setVisible(true);
            }
            this.dispose();
        } else {
            if (jugador.equals("1")) {
                Juego.setUrlFichaJ1("/Recursos/ficha-purple-guy-tablero.png");
                Juego.setIdFicha1(1);
                ficha1 = "purple-guy";
                new SeleccionFicha("Competencia","2","1").setVisible(true);
                this.dispose();
            } else {
                Juego.setUrlFichaJ2("/Recursos/ficha-purple-guy-tablero.png");
                Juego.setIdFicha2(1);
                ficha2 = "purple-guy";
                if (Juego.getUrlTablero().equals("/Recursos/tablero_dificil.jpg")) {
                    new PartidaCompetenciaHard(this.modalidad,ficha1,ficha2).setVisible(true);
                } else {
                    new PartidaCompetencia(this.modalidad,ficha1,ficha2).setVisible(true);
                }  
                this.dispose();
            }
        }
    }//GEN-LAST:event_btnFicha1ActionPerformed

    private void rSButtonShapeIcon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonShapeIcon1ActionPerformed
        new SeleccionTablero(modalidad).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rSButtonShapeIcon1ActionPerformed

    private void btnFicha3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFicha3ActionPerformed
        if (modalidad.equals("Individual")) {
            Juego.setUrlFichaJ1("/Recursos/ficha-spiderman-tablero.png");
            Juego.setIdFicha1(3);
            if (Juego.getUrlTablero().equals("/Recursos/tablero_dificil.jpg")) {
                new PartidaHard(this.modalidad, "spiderman").setVisible(true);
            } else {
                new Partida(this.modalidad, "spiderman").setVisible(true);
            }
            this.dispose();
        } else {
            if (jugador.equals("1")) {
                Juego.setUrlFichaJ1("/Recursos/ficha-spiderman-tablero.png");
                Juego.setIdFicha1(3);
                ficha1 = "spiderman";
                new SeleccionFicha("Competencia","2","3").setVisible(true);
                this.dispose();
            } else {
                Juego.setUrlFichaJ2("/Recursos/ficha-spiderman-tablero.png");
                Juego.setIdFicha2(3);
                ficha2 = "spiderman";
                if (Juego.getUrlTablero().equals("/Recursos/tablero_dificil.jpg")) {
                    new PartidaCompetenciaHard(this.modalidad,ficha1,ficha2).setVisible(true);
                } else {
                    new PartidaCompetencia(this.modalidad,ficha1,ficha2).setVisible(true);
                }  
                this.dispose();
            }
        }
    }//GEN-LAST:event_btnFicha3ActionPerformed

    private void btnFicha4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFicha4ActionPerformed
        if (modalidad.equals("Individual")) {
            Juego.setUrlFichaJ1("/Recursos/ficha-sailormoon-tablero.png");
            Juego.setIdFicha1(4);
            if (Juego.getUrlTablero().equals("/Recursos/tablero_dificil.jpg")) {
                new PartidaHard(this.modalidad, "sailormoon").setVisible(true);
            } else {
                new Partida(this.modalidad, "sailormoon").setVisible(true);
            }
            this.dispose();
        } else {
            if (jugador.equals("1")) {
                Juego.setUrlFichaJ1("/Recursos/ficha-sailormoon-tablero.png");
                Juego.setIdFicha1(4);
                ficha1 = "sailormoon";
                new SeleccionFicha("Competencia","2","4").setVisible(true);
                this.dispose();
            } else {
                Juego.setUrlFichaJ2("/Recursos/ficha-sailormoon-tablero.png");
                Juego.setIdFicha2(4);
                ficha2 = "sailormoon";
                if (Juego.getUrlTablero().equals("/Recursos/tablero_dificil.jpg")) {
                    new PartidaCompetenciaHard(this.modalidad,ficha1,ficha2).setVisible(true);
                } else {
                    new PartidaCompetencia(this.modalidad,ficha1,ficha2).setVisible(true);
                }  
                this.dispose();
            }
        }
    }//GEN-LAST:event_btnFicha4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeleccionFicha(args[0],args[1],args[2]).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialOne btnFicha1;
    private RSMaterialComponent.RSButtonMaterialOne btnFicha2;
    private RSMaterialComponent.RSButtonMaterialOne btnFicha3;
    private RSMaterialComponent.RSButtonMaterialOne btnFicha4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private RSMaterialComponent.RSButtonShapeIcon rSButtonShapeIcon1;
    private RSMaterialComponent.RSPanelBorder rSPanelBorder1;
    private RSMaterialComponent.RSPanelBorder rSPanelBorder2;
    private RSMaterialComponent.RSPanelBorder rSPanelBorder3;
    private RSMaterialComponent.RSPanelBorder rSPanelBorder4;
    // End of variables declaration//GEN-END:variables
}
