/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Helpers.Funciones;

/**
 *
 * @author Diego
 */
public class Tableros extends javax.swing.JFrame {

    /**
     * Creates new form Selecciones
     */
    public Tableros() {
        initComponents();
        this.setLocationRelativeTo(null);
        urlTablero1 = "/Recursos/tablero_facil.jpg";
        urlTablero2 = "/Recursos/tablero_medio.jpg";
        urlTablero3 = "/Recursos/tablero_dificil.jpg";
    }
    
    Funciones obj = new Funciones();
    
    String urlTablero1,urlTablero2,urlTablero3;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rSPanelBorder7 = new RSMaterialComponent.RSPanelBorder();
        btnTablero2 = new RSMaterialComponent.RSButtonMaterialOne();
        lblTablero4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rSPanelBorder8 = new RSMaterialComponent.RSPanelBorder();
        btnTablero3 = new RSMaterialComponent.RSButtonMaterialOne();
        lblTablero3 = new javax.swing.JLabel();
        rSPanelBorder6 = new RSMaterialComponent.RSPanelBorder();
        btnTablero1 = new RSMaterialComponent.RSButtonMaterialOne();
        lblTablero2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel100 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        jLabel103 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        jLabel106 = new javax.swing.JLabel();
        jLabel107 = new javax.swing.JLabel();
        jLabel108 = new javax.swing.JLabel();
        jLabel109 = new javax.swing.JLabel();
        jLabel110 = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel112 = new javax.swing.JLabel();
        jLabel113 = new javax.swing.JLabel();
        jLabel114 = new javax.swing.JLabel();
        jLabel115 = new javax.swing.JLabel();
        jLabel116 = new javax.swing.JLabel();
        jLabel117 = new javax.swing.JLabel();
        jLabel118 = new javax.swing.JLabel();
        jLabel119 = new javax.swing.JLabel();
        jLabel120 = new javax.swing.JLabel();
        jLabel121 = new javax.swing.JLabel();
        jLabel122 = new javax.swing.JLabel();
        jLabel123 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel124 = new javax.swing.JLabel();
        jLabel125 = new javax.swing.JLabel();
        jLabel126 = new javax.swing.JLabel();
        jLabel127 = new javax.swing.JLabel();
        jLabel128 = new javax.swing.JLabel();
        jLabel129 = new javax.swing.JLabel();
        jLabel130 = new javax.swing.JLabel();
        jLabel131 = new javax.swing.JLabel();
        jLabel132 = new javax.swing.JLabel();
        jLabel133 = new javax.swing.JLabel();
        jLabel134 = new javax.swing.JLabel();
        jLabel135 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel136 = new javax.swing.JLabel();
        jLabel137 = new javax.swing.JLabel();
        jLabel138 = new javax.swing.JLabel();
        jLabel139 = new javax.swing.JLabel();
        jLabel140 = new javax.swing.JLabel();
        jLabel141 = new javax.swing.JLabel();
        jLabel142 = new javax.swing.JLabel();
        jLabel143 = new javax.swing.JLabel();
        jLabel144 = new javax.swing.JLabel();
        jLabel145 = new javax.swing.JLabel();
        jLabel146 = new javax.swing.JLabel();
        jLabel147 = new javax.swing.JLabel();
        rSButtonShapeIcon1 = new RSMaterialComponent.RSButtonShapeIcon();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSPanelBorder7.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelBorder7.setWidthBorder(2);
        rSPanelBorder7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTablero2.setBackground(new java.awt.Color(0, 102, 102));
        btnTablero2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnTablero2.setText("Tablero Intermedio");
        btnTablero2.setBackgroundHover(new java.awt.Color(153, 153, 153));
        btnTablero2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnTablero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTablero2ActionPerformed(evt);
            }
        });
        rSPanelBorder7.add(btnTablero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 400, 60));

        lblTablero4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/tablero_medio_vista.jpg"))); // NOI18N
        lblTablero4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblTablero4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTablero4MouseClicked(evt);
            }
        });
        rSPanelBorder7.add(lblTablero4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 280));

        jPanel1.add(rSPanelBorder7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 400, 340));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("TABLEROS DEL JUEGO");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(491, 40, 270, 50));

        rSPanelBorder8.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelBorder8.setWidthBorder(2);
        rSPanelBorder8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTablero3.setBackground(new java.awt.Color(51, 0, 153));
        btnTablero3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnTablero3.setText("Tablero Dificil");
        btnTablero3.setBackgroundHover(new java.awt.Color(153, 153, 153));
        btnTablero3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnTablero3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTablero3ActionPerformed(evt);
            }
        });
        rSPanelBorder8.add(btnTablero3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 400, 60));

        lblTablero3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/tablero_dificil_vista.jpg"))); // NOI18N
        lblTablero3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblTablero3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTablero3MouseClicked(evt);
            }
        });
        rSPanelBorder8.add(lblTablero3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 280));

        jPanel1.add(rSPanelBorder8, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 130, 400, 340));

        rSPanelBorder6.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelBorder6.setWidthBorder(2);
        rSPanelBorder6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTablero1.setBackground(new java.awt.Color(0, 153, 153));
        btnTablero1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnTablero1.setText("Tablero Facil");
        btnTablero1.setBackgroundHover(new java.awt.Color(153, 153, 153));
        btnTablero1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnTablero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTablero1ActionPerformed(evt);
            }
        });
        rSPanelBorder6.add(btnTablero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 400, 60));

        lblTablero2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/tablero_facil-vista.jpg"))); // NOI18N
        lblTablero2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblTablero2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTablero2MouseClicked(evt);
            }
        });
        rSPanelBorder6.add(lblTablero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 280));

        jPanel1.add(rSPanelBorder6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 400, 340));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 530, 10));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente punteria.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 40, 110, 50));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel4.setText("Escaleras");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel5.setText(" Casillas");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel3.setText(" Serpientes");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("32");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 20));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel10.setText(" Casillas");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel11.setText("Escaleras");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("4");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 20));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel14.setText(" Serpientes");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("5");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, 20));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel28.setText("Escaleras");
        jPanel6.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel29.setText(" Casillas");
        jPanel6.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel30.setText(" Serpientes");
        jPanel6.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel31.setText("3");
        jPanel6.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, 20));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel32.setText("24");
        jPanel6.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 20));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel33.setText("5");
        jPanel6.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 20));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel34.setText(" Casillas");
        jPanel6.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel35.setText("Escaleras");
        jPanel6.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel36.setText("5");
        jPanel6.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 20));

        jLabel37.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel37.setText("24");
        jPanel6.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 20));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel38.setText(" Serpientes");
        jPanel6.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel39.setText("3");
        jPanel6.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, 20));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 490, 400, 130));

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel40.setText("Escaleras");
        jPanel7.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel41.setText(" Casillas");
        jPanel7.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel42.setText(" Serpientes");
        jPanel7.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel43.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel43.setText("3");
        jPanel7.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, 20));

        jLabel44.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel44.setText("24");
        jPanel7.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 20));

        jLabel45.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel45.setText("5");
        jPanel7.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 20));

        jLabel46.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel46.setText(" Casillas");
        jPanel7.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel47.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel47.setText("Escaleras");
        jPanel7.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel48.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel48.setText("5");
        jPanel7.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 20));

        jLabel49.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel49.setText("24");
        jPanel7.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 20));

        jLabel50.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel50.setText(" Serpientes");
        jPanel7.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel51.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel51.setText("3");
        jPanel7.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, 20));

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel52.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel52.setText("Escaleras");
        jPanel8.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel53.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel53.setText(" Casillas");
        jPanel8.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel54.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel54.setText(" Serpientes");
        jPanel8.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel55.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel55.setText("3");
        jPanel8.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, 20));

        jLabel56.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel56.setText("24");
        jPanel8.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 20));

        jLabel57.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel57.setText("5");
        jPanel8.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 20));

        jLabel58.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel58.setText(" Casillas");
        jPanel8.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel59.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel59.setText("Escaleras");
        jPanel8.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel60.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel60.setText("5");
        jPanel8.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 20));

        jLabel61.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel61.setText("24");
        jPanel8.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 20));

        jLabel62.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel62.setText(" Serpientes");
        jPanel8.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel63.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel63.setText("3");
        jPanel8.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, 20));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 490, 400, 130));

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 490, 400, 130));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 490, 400, 130));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel16.setText("Escaleras");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel17.setText(" Casillas");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel18.setText(" Serpientes");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel22.setText(" Casillas");
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel23.setText("Escaleras");
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setText("3");
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 20));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setText("40");
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 20));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel26.setText(" Serpientes");
        jPanel5.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel27.setText("9");
        jPanel5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, 20));

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel64.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel64.setText("Escaleras");
        jPanel9.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel65.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel65.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel65.setText(" Casillas");
        jPanel9.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel66.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel66.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel66.setText(" Serpientes");
        jPanel9.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel67.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel67.setText("3");
        jPanel9.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, 20));

        jLabel68.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel68.setText("24");
        jPanel9.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 20));

        jLabel69.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel69.setText("5");
        jPanel9.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 20));

        jLabel70.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel70.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel70.setText(" Casillas");
        jPanel9.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel71.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel71.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel71.setText("Escaleras");
        jPanel9.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel72.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel72.setText("5");
        jPanel9.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 20));

        jLabel73.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel73.setText("24");
        jPanel9.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 20));

        jLabel74.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel74.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel74.setText(" Serpientes");
        jPanel9.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel75.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel75.setText("3");
        jPanel9.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, 20));

        jPanel5.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 400, 130));

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel76.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel76.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel76.setText("Escaleras");
        jPanel10.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel77.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel77.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel77.setText(" Casillas");
        jPanel10.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel78.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel78.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel78.setText(" Serpientes");
        jPanel10.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel79.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel79.setText("3");
        jPanel10.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, 20));

        jLabel80.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel80.setText("24");
        jPanel10.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 20));

        jLabel81.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel81.setText("5");
        jPanel10.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 20));

        jLabel82.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel82.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel82.setText(" Casillas");
        jPanel10.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel83.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel83.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel83.setText("Escaleras");
        jPanel10.add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel84.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel84.setText("5");
        jPanel10.add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 20));

        jLabel85.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel85.setText("24");
        jPanel10.add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 20));

        jLabel86.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel86.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel86.setText(" Serpientes");
        jPanel10.add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel87.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel87.setText("3");
        jPanel10.add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, 20));

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel88.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel88.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel88.setText("Escaleras");
        jPanel11.add(jLabel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel89.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel89.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel89.setText(" Casillas");
        jPanel11.add(jLabel89, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel90.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel90.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel90.setText(" Serpientes");
        jPanel11.add(jLabel90, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel91.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel91.setText("3");
        jPanel11.add(jLabel91, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, 20));

        jLabel92.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel92.setText("24");
        jPanel11.add(jLabel92, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 20));

        jLabel93.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel93.setText("5");
        jPanel11.add(jLabel93, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 20));

        jLabel94.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel94.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel94.setText(" Casillas");
        jPanel11.add(jLabel94, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel95.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel95.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel95.setText("Escaleras");
        jPanel11.add(jLabel95, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel96.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel96.setText("5");
        jPanel11.add(jLabel96, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 20));

        jLabel97.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel97.setText("24");
        jPanel11.add(jLabel97, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 20));

        jLabel98.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel98.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel98.setText(" Serpientes");
        jPanel11.add(jLabel98, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel99.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel99.setText("3");
        jPanel11.add(jLabel99, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, 20));

        jPanel10.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 400, 130));

        jPanel5.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 400, 130));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 490, 400, 130));

        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel100.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel100.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel100.setText("Escaleras");
        jPanel12.add(jLabel100, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel101.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel101.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel101.setText(" Casillas");
        jPanel12.add(jLabel101, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel102.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel102.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel102.setText(" Serpientes");
        jPanel12.add(jLabel102, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel103.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel103.setText("3");
        jPanel12.add(jLabel103, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, 20));

        jLabel104.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel104.setText("24");
        jPanel12.add(jLabel104, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 20));

        jLabel105.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel105.setText("5");
        jPanel12.add(jLabel105, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 20));

        jLabel106.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel106.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel106.setText(" Casillas");
        jPanel12.add(jLabel106, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel107.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel107.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel107.setText("Escaleras");
        jPanel12.add(jLabel107, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel108.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel108.setText("5");
        jPanel12.add(jLabel108, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 20));

        jLabel109.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel109.setText("24");
        jPanel12.add(jLabel109, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 20));

        jLabel110.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel110.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel110.setText(" Serpientes");
        jPanel12.add(jLabel110, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel111.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel111.setText("3");
        jPanel12.add(jLabel111, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, 20));

        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel112.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel112.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel112.setText("Escaleras");
        jPanel13.add(jLabel112, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel113.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel113.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel113.setText(" Casillas");
        jPanel13.add(jLabel113, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel114.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel114.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel114.setText(" Serpientes");
        jPanel13.add(jLabel114, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel115.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel115.setText("3");
        jPanel13.add(jLabel115, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, 20));

        jLabel116.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel116.setText("24");
        jPanel13.add(jLabel116, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 20));

        jLabel117.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel117.setText("5");
        jPanel13.add(jLabel117, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 20));

        jLabel118.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel118.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel118.setText(" Casillas");
        jPanel13.add(jLabel118, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel119.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel119.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel119.setText("Escaleras");
        jPanel13.add(jLabel119, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel120.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel120.setText("5");
        jPanel13.add(jLabel120, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 20));

        jLabel121.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel121.setText("24");
        jPanel13.add(jLabel121, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 20));

        jLabel122.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel122.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel122.setText(" Serpientes");
        jPanel13.add(jLabel122, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel123.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel123.setText("3");
        jPanel13.add(jLabel123, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, 20));

        jPanel12.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 400, 130));

        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel124.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel124.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel124.setText("Escaleras");
        jPanel14.add(jLabel124, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel125.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel125.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel125.setText(" Casillas");
        jPanel14.add(jLabel125, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel126.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel126.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel126.setText(" Serpientes");
        jPanel14.add(jLabel126, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel127.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel127.setText("3");
        jPanel14.add(jLabel127, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, 20));

        jLabel128.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel128.setText("24");
        jPanel14.add(jLabel128, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 20));

        jLabel129.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel129.setText("5");
        jPanel14.add(jLabel129, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 20));

        jLabel130.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel130.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel130.setText(" Casillas");
        jPanel14.add(jLabel130, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel131.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel131.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel131.setText("Escaleras");
        jPanel14.add(jLabel131, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel132.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel132.setText("5");
        jPanel14.add(jLabel132, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 20));

        jLabel133.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel133.setText("24");
        jPanel14.add(jLabel133, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 20));

        jLabel134.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel134.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel134.setText(" Serpientes");
        jPanel14.add(jLabel134, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel135.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel135.setText("3");
        jPanel14.add(jLabel135, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, 20));

        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel136.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel136.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel136.setText("Escaleras");
        jPanel15.add(jLabel136, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel137.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel137.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel137.setText(" Casillas");
        jPanel15.add(jLabel137, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel138.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel138.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel138.setText(" Serpientes");
        jPanel15.add(jLabel138, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel139.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel139.setText("3");
        jPanel15.add(jLabel139, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, 20));

        jLabel140.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel140.setText("24");
        jPanel15.add(jLabel140, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 20));

        jLabel141.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel141.setText("5");
        jPanel15.add(jLabel141, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 20));

        jLabel142.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel142.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casillas.png"))); // NOI18N
        jLabel142.setText(" Casillas");
        jPanel15.add(jLabel142, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel143.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel143.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escalera.png"))); // NOI18N
        jLabel143.setText("Escaleras");
        jPanel15.add(jLabel143, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel144.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel144.setText("5");
        jPanel15.add(jLabel144, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 20));

        jLabel145.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel145.setText("24");
        jPanel15.add(jLabel145, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 20));

        jLabel146.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel146.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serpiente.png"))); // NOI18N
        jLabel146.setText(" Serpientes");
        jPanel15.add(jLabel146, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel147.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel147.setText("3");
        jPanel15.add(jLabel147, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, 20));

        jPanel14.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 400, 130));

        jPanel12.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 400, 130));

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 400, 130));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 1320, 650));

        rSButtonShapeIcon1.setBackground(new java.awt.Color(0, 153, 153));
        rSButtonShapeIcon1.setText("Regresar al menu");
        rSButtonShapeIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ARROW_BACK);
        rSButtonShapeIcon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonShapeIcon1ActionPerformed(evt);
            }
        });
        getContentPane().add(rSButtonShapeIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 190, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/fondoEstadisticas.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblTablero2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTablero2MouseClicked
        new VisorTablero(urlTablero2).setVisible(true);
    }//GEN-LAST:event_lblTablero2MouseClicked

    private void lblTablero3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTablero3MouseClicked
        new VisorTablero(urlTablero3).setVisible(true);
    }//GEN-LAST:event_lblTablero3MouseClicked

    private void rSButtonShapeIcon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonShapeIcon1ActionPerformed
        MenuPrincipal a = new MenuPrincipal();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rSButtonShapeIcon1ActionPerformed

    private void btnTablero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTablero1ActionPerformed
        new VisorTablero(urlTablero1).setVisible(true);
    }//GEN-LAST:event_btnTablero1ActionPerformed

    private void btnTablero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTablero2ActionPerformed
        new VisorTablero(urlTablero2).setVisible(true);
    }//GEN-LAST:event_btnTablero2ActionPerformed

    private void btnTablero3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTablero3ActionPerformed
        new VisorTablero(urlTablero3).setVisible(true);
    }//GEN-LAST:event_btnTablero3ActionPerformed

    private void lblTablero4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTablero4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTablero4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tableros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tableros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tableros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tableros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tableros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialOne btnTablero1;
    private RSMaterialComponent.RSButtonMaterialOne btnTablero2;
    private RSMaterialComponent.RSButtonMaterialOne btnTablero3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel132;
    private javax.swing.JLabel jLabel133;
    private javax.swing.JLabel jLabel134;
    private javax.swing.JLabel jLabel135;
    private javax.swing.JLabel jLabel136;
    private javax.swing.JLabel jLabel137;
    private javax.swing.JLabel jLabel138;
    private javax.swing.JLabel jLabel139;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel140;
    private javax.swing.JLabel jLabel141;
    private javax.swing.JLabel jLabel142;
    private javax.swing.JLabel jLabel143;
    private javax.swing.JLabel jLabel144;
    private javax.swing.JLabel jLabel145;
    private javax.swing.JLabel jLabel146;
    private javax.swing.JLabel jLabel147;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblTablero2;
    private javax.swing.JLabel lblTablero3;
    private javax.swing.JLabel lblTablero4;
    private RSMaterialComponent.RSButtonShapeIcon rSButtonShapeIcon1;
    private RSMaterialComponent.RSPanelBorder rSPanelBorder6;
    private RSMaterialComponent.RSPanelBorder rSPanelBorder7;
    private RSMaterialComponent.RSPanelBorder rSPanelBorder8;
    // End of variables declaration//GEN-END:variables
}
